Issue1011 propagation storage model
RWTH-EBC/AixLib pull request #1013
Opened 2020-10-01 15:47 UTC by LauraMaier

This solves issue 1011.
The model AixLib.Fluid.Storage.Storage included hard coding and proper propagation of crucial parameters was missing.
The following changes were made:

Propagation of crucial parameters in sub models layer and layer_HE like:
- [ ] m_flow_nominal
- [ ] energyDynamics 
- [ ] m_flow_small
- [ ] Initialization p_start and T_start

- [ ] Replacement of hard-coded m_flow_nominal of layer and layer_HE

2020-10-22 15:06 UTC, PMehrfeld commented
@LauraMaier : If this is ready for review, please assign someone ;)

2020-10-23 07:59 UTC, PMehrfeld requested changes

2020-10-23 07:59 UTC, PMehrfeld commented on AixLib/Fluid/Storage/Storage.mo
> +                              each V = V / n, redeclare package Medium = Medium,
`final` everything. If possible also in all other instances ;)

2020-10-23 07:59 UTC, PMehrfeld commented on AixLib/Fluid/Storage/Storage.mo
> +    each m_flow_nominal=m_flow_nominal_layer)      annotation(Placement(transformation(extent = {{-10, -10}, {10, 10}}, rotation = 90, origin = {0, 0})));
`final`

2020-10-23 07:59 UTC, PMehrfeld commented on AixLib/Fluid/Storage/Storage.mo
> +    each m_flow_nominal=m_flow_nominal_HE)               annotation(Placement(transformation(extent = {{-10, -10}, {10, 10}}, rotation = 90, origin = {84, 0})));
Heat Exchanger is typically abbreviated with HX. You could correct it at least for `m_flow_nominal_HE` since for this no inter-model refactoring or conversion script is necessary.

2020-10-23 07:59 UTC, PMehrfeld commented on AixLib/Fluid/Storage/Storage.mo
> +  parameter Modelica.SIunits.MassFlowRate m_flow_nominal_layer=0.01
Delete default value!

2020-10-23 07:59 UTC, PMehrfeld commented on AixLib/Fluid/Storage/Storage.mo
> +  parameter Modelica.SIunits.MassFlowRate m_flow_nominal_HE=0.01
Delete default value!

2020-10-23 07:59 UTC, PMehrfeld commented on AixLib/Fluid/Storage/Storage.mo
> +   parameter Modelica.SIunits.MassFlowRate m_flow_small_layer_HE=1E-4*abs(m_flow_nominal_HE)
correct to `m_flow_small_HX`

2020-10-29 08:41 UTC, LauraMaier commented on AixLib/Fluid/Storage/Storage.mo
> +    each m_flow_nominal=m_flow_nominal_HE)               annotation(Placement(transformation(extent = {{-10, -10}, {10, 10}}, rotation = 90, origin = {84, 0})));
Thanks for your suggestion @PMehrfeld. I would prefer to stay with the HE abbreviation as the layers for the heat exchanger are introduced as layer_HE, too. If I only changed HE to HX for the parameter m_flow_nominal_HE, we would not achieve consistency within the model. Is that ok?

2020-10-29 08:46 UTC, LauraMaier commented on AixLib/Fluid/Storage/Storage.mo
> +   parameter Modelica.SIunits.MassFlowRate m_flow_small_layer_HE=1E-4*abs(m_flow_nominal_HE)
Thanks for your suggestion @PMehrfeld. I would prefer to stay with the HE abbreviation as the layers for the heat exchanger are introduced as layer_HE, too. If I only changed HE to HX for the parameter m_flow_nominal_HE, we would not achieve consistency within the model. Is that ok?

2020-10-29 09:02 UTC, LauraMaier commented on AixLib/Fluid/Storage/Storage.mo
> +                              each V = V / n, redeclare package Medium = Medium,
Done :)

2020-10-29 09:02 UTC, LauraMaier commented on AixLib/Fluid/Storage/Storage.mo
> +    each m_flow_nominal=m_flow_nominal_layer)      annotation(Placement(transformation(extent = {{-10, -10}, {10, 10}}, rotation = 90, origin = {0, 0})));
Done :)

2020-10-29 09:02 UTC, LauraMaier commented on AixLib/Fluid/Storage/Storage.mo
> +  parameter Modelica.SIunits.MassFlowRate m_flow_nominal_HE=0.01
Done :)

2020-10-29 09:50 UTC, PMehrfeld commented on AixLib/Fluid/Storage/Storage.mo
> +  parameter Modelica.Fluid.Types.Dynamics energyDynamics=Modelica.Fluid.Types.Dynamics.DynamicFreeInitial
If this refers only to the layers, you could state this in the name or at least the description. Normally, we would need individual sets of parameters for layers, HXs fluid, and dry masses regarding dynamics and initialization.

2020-10-29 09:51 UTC, PMehrfeld approved these changes
Only one comment. But PR is approved.

2020-10-29 13:05 UTC, LauraMaier commented on AixLib/Fluid/Storage/Storage.mo
> +  parameter Modelica.Fluid.Types.Dynamics energyDynamics=Modelica.Fluid.Types.Dynamics.DynamicFreeInitial
Good point! I will add this information in die description

2020-11-30 16:03 UTC, PMehrfeld approved these changes
When CI runner works again, merge after successful CI.

2020-12-02 14:53 UTC, merged