Issue937 integrate three way table valve into hydraulic modules
RWTH-EBC/AixLib pull request #1038
Opened 2020-10-29 17:30 UTC by alexanderAKU

> Thank you for making a Pull Request to AixLib!

> Please consider these points before submitting:
> - Mention the issue that this Pull Request intends to solve, and briefly describe what the main changes are.
> - Make sure all new code follows our [Modelica Guidelines](https://github.com/RWTH-EBC/AixLib/wiki/Modelica-guidelines)
> - Make sure all new models include documentation as described in the [Documentation Wiki-Page](https://github.com/RWTH-EBC/AixLib/wiki/Documentation) and are demonstrated by suitable examples

> If you know someone who could review your code, please use the *Reviewer* function on the right to ask for a review and also assign the PR to them. If not, no worries, we will find someone for you.

> Thanks again for your PR! You can delete these first lines before submitting your PR.

2021-02-09 12:44 UTC, PMehrfeld commented on AixLib/Systems/HydraulicModules/BaseClasses/PumpInterface_PumpHeadControlled.mo
> +    final energyDynamics=Modelica.Fluid.Types.Dynamics.DynamicFreeInitial,
@alexanderAKU and @LauraMaier : I just saw this "by accident". I assume this needs to be changed back to `energyDynamics`?!

2021-02-09 12:45 UTC, PMehrfeld commented on AixLib/Systems/HydraulicModules/BaseClasses/PumpInterface_PumpSpeedControlled.mo
> +    final energyDynamics=Modelica.Fluid.Types.Dynamics.DynamicFreeInitial,
see other comment

2021-04-26 14:07 UTC, alexanderAKU commented on AixLib/Systems/HydraulicModules/BaseClasses/PumpInterface_PumpSpeedControlled.mo
> +    final energyDynamics=Modelica.Fluid.Types.Dynamics.DynamicFreeInitial,
@PMehrfeld this was on prupose: if the energyDynamics is forwared, it leads to an error in combination with the plugFlowPipe since the energyDynamics and MassDynamics in the plugFlowPipe is FixedInitial and can't be changed. However, the FreeInitial in the pumpInterface does not lead to an underspecified simulation

2021-04-27 05:59 UTC, PMehrfeld commented on AixLib/Systems/HydraulicModules/BaseClasses/PumpInterface_PumpSpeedControlled.mo
> +    final energyDynamics=Modelica.Fluid.Types.Dynamics.DynamicFreeInitial,
@alexanderAKU: You said "**does not lead**". Was this correct? Since `DynamicFreeInitial` normally leads to unspecified initial conditions.

In any case, thanks for the explanation.

2021-04-29 19:01 UTC, alexanderAKU commented on AixLib/Systems/HydraulicModules/BaseClasses/PumpInterface_PumpSpeedControlled.mo
> +    final energyDynamics=Modelica.Fluid.Types.Dynamics.DynamicFreeInitial,
There is no warning that the initial conditions are not fully specified.

2021-05-06 12:43 UTC, LauraMaier requested changes

2021-05-06 12:43 UTC, LauraMaier commented on AixLib/Systems/HydraulicModules/BaseClasses/PumpInterface_PumpHeadControlled.mo
> +  parameter AixLib.DataBase.Pumps.PumpPolynomialBased.PumpBaseRecord pumpParam = AixLib.DataBase.Pumps.PumpPolynomialBased.PumpBaseRecord()
Maybe replaceable here?

2021-05-06 12:43 UTC, LauraMaier commented on AixLib/Systems/HydraulicModules/BaseClasses/PumpInterface_PumpSpeedControlled.mo
> +  parameter AixLib.DataBase.Pumps.PumpPolynomialBased.PumpBaseRecord pumpParam=AixLib.DataBase.Pumps.PumpPolynomialBased.PumpBaseRecord()
s. comment above regarding introducing replaceable parameters

2021-05-06 12:43 UTC, LauraMaier commented on AixLib/Systems/HydraulicModules/Example/Admix.mo
> +    valveCharacteristic=Fluid.Actuators.Valves.Data.LinearEqualPercentage(),
I am not 100 % sure, but didn't we want to only include full model paths like `AixLib.Fluid.Acturators.Valves.Data.LinearEqualPercentage()` ?

2021-05-06 12:43 UTC, LauraMaier commented on AixLib/Systems/HydraulicModules/Example/ERC_ExperimentalHall_CoolingCircuit.mo
> +    valveCharacteristic=Fluid.Actuators.Valves.Data.LinearEqualPercentage(),
Same here: full Model paths?

2021-05-06 12:43 UTC, LauraMaier commented on AixLib/Systems/HydraulicModules/Example/Injection.mo
> +    valveCharacteristic=Fluid.Actuators.Valves.Data.LinearEqualPercentage(),
same here: full model paths?

2021-05-06 12:43 UTC, LauraMaier commented on AixLib/Systems/HydraulicModules/Injection.mo
> +  parameter Fluid.Actuators.Valves.Data.GenericThreeWay valveCharacteristic "Valve characteristic of three way valve"
full model path?

2021-05-06 12:43 UTC, LauraMaier commented on AixLib/Systems/HydraulicModules/Injection.mo
> +within AixLib.Systems.HydraulicModules;
General comment: The graphical overview looks a bit messy. Could you maybe tidy it up a bit? :-)

2021-05-06 12:43 UTC, LauraMaier commented on AixLib/Systems/HydraulicModules/Injection.mo
> +  Fluid.Actuators.Valves.ThreeWayTable                        valve(
Full model path? Maybe check for the whole PR? :-)

2021-05-06 12:43 UTC, LauraMaier commented on AixLib/Systems/HydraulicModules/Injection.mo
> +    dpFixed_nominal={10,10},
Wouldn't it be nice to propagate the `dpFixed_nominal `value and `tau `to enable further parameterization?

2021-05-06 12:43 UTC, LauraMaier commented on AixLib/Systems/HydraulicModules/Injection.mo
> +<li>August 09, 2018, by Alexander K&uuml;mpel:<br/>Extension from base PartioalHydraulicModuls</li>
maybe update date? This applies to all models :-)

2021-05-06 16:54 UTC, alexanderAKU commented on AixLib/Fluid/Actuators/Valves/Data/GenericThreeWay.mo
> +     "Valve characteristics for gate B to AB";
a,b and ab are usually used for the gates

2021-05-06 16:54 UTC, alexanderAKU commented on AixLib/Fluid/Actuators/Valves/Data/LinearLinear.mo
> +record LinearLinear = GenericThreeWay(a_ab = Linear(), b_ab=Linear())
as above

2021-05-06 17:30 UTC, alexanderAKU commented on AixLib/Systems/HydraulicModules/Admix.mo
> -    l={0.001,0.001},
@LauraMaier Which parameter?

2021-05-06 17:32 UTC, alexanderAKU commented on AixLib/Systems/HydraulicModules/BaseClasses/PumpInterface_PumpHeadControlled.mo
> +    final energyDynamics=Modelica.Fluid.Types.Dynamics.DynamicFreeInitial,
as discussed

2021-05-06 17:36 UTC, alexanderAKU commented on AixLib/Fluid/Actuators/Valves/Data/GenericThreeWay.mo
> +     "Valve characteristics for gate B to AB";
usually a,b and ab is used for valves

2021-05-06 17:36 UTC, alexanderAKU commented on AixLib/Fluid/Actuators/Valves/Data/LinearLinear.mo
> +record LinearLinear = GenericThreeWay(a_ab = Linear(), b_ab=Linear())
as above

2021-05-06 17:37 UTC, alexanderAKU commented on AixLib/Fluid/Movers/PumpsPolynomialBased/Examples/PumpSpeedControlledDpV.mo
> +  "Testing the pump dp-var algorithm with the new \"one record\" pump model with internal speed limitation (instead of pump head limitation)."
done

2021-05-06 17:37 UTC, alexanderAKU commented on AixLib/Fluid/Movers/PumpsPolynomialBased/Examples/PumpSpeedControlledTest.mo
>    "Testing the pump speed algorithm with the new \"one record\" pump model."
done

2021-05-06 17:37 UTC, alexanderAKU commented on AixLib/Systems/HydraulicModules/Injection.mo
> +  parameter Fluid.Actuators.Valves.Data.GenericThreeWay valveCharacteristic "Valve characteristic of three way valve"
full path is not used in the models, so  i would keep it as it is now

2021-05-06 17:42 UTC, alexanderAKU commented on AixLib/Systems/HydraulicModules/Injection.mo
> +within AixLib.Systems.HydraulicModules;
Done

2021-05-06 17:44 UTC, alexanderAKU commented on AixLib/Systems/HydraulicModules/Injection.mo
> +    dpFixed_nominal={10,10},
parameters can be modified in the lower level

2021-06-10 15:27 UTC, phillipstoffel approved these changes

2021-06-17 12:29 UTC, LauraMaier approved these changes

2021-06-17 12:29 UTC, merged