Issue784 ahu with hydraulic modules
RWTH-EBC/AixLib pull request #1039
Opened 2020-10-29 17:30 UTC by alexanderAKU

> Thank you for making a Pull Request to AixLib!

> Please consider these points before submitting:
> - Mention the issue that this Pull Request intends to solve, and briefly describe what the main changes are.
> - Make sure all new code follows our [Modelica Guidelines](https://github.com/RWTH-EBC/AixLib/wiki/Modelica-guidelines)
> - Make sure all new models include documentation as described in the [Documentation Wiki-Page](https://github.com/RWTH-EBC/AixLib/wiki/Documentation) and are demonstrated by suitable examples

> If you know someone who could review your code, please use the *Reviewer* function on the right to ask for a review and also assign the PR to them. If not, no worries, we will find someone for you.

> Thanks again for your PR! You can delete these first lines before submitting your PR.

2020-10-30 15:30 UTC, KremerMartin requested changes
Thanks for the contribution and really good work.
Some Changes need to be provided to the models:

- [x] The Initial Conditions in the Examples `GenericAHU` and `EONERC_AHU2` are not fully specified.

- [ ] Unit-Tests are missing for the examples (also for the old examples of the sub-components)

- [x] Comments are missing in `CtrAHUBasic` for bus-connectors and constants

- [ ] Comments are missing in `CTRRegBasic` for bus-connectors and constants

- [ ] Comments are missing in `GenericAHU` for components and Sensors

- [ ] The Modelica-Guidelines are not fully respected. Please check again for naming-conventions.

- [ ] Just a suggestion: The extract air is abbreviated with `Ret` (for aexample `fanRet`). Since the DIN 13779 provides _Eta_ as abbreviation for the extract air, it would be more applicable to use this abbreviation instead. Same goes for `senTExh`, that would then be `senTEha`.

2020-10-30 15:30 UTC, KremerMartin commented on AixLib/Systems/ModularAHU/GenericAHU.mo
> +    "Fluid connector a1 (positive design flow direction is from port_a1 to port_b1)"
Should be a2 here in the comment. ;)

2020-10-30 15:30 UTC, KremerMartin commented on AixLib/Systems/ModularAHU/GenericAHU.mo
> +    "Fluid connector b1 (positive design flow direction is from port_a1 to port_b1)"
Same here: b2

2020-10-30 15:30 UTC, KremerMartin commented on AixLib/Systems/ModularAHU/GenericAHU.mo
> +    "Fluid connector a2 (positive design flow direction is from port_a2 to port_b2)"
Same here: a3 instead of a2 (also b3)

2021-04-23 06:40 UTC, KremerMartin requested changes
When  checking, an error and warnings occurs for the register module:
![grafik](https://user-images.githubusercontent.com/48821826/115829040-c36b0400-a40e-11eb-9f6a-8f4fd1498310.png)
Maybe the warnings can be fixed by giving some start values for m_flow_nominal:
![grafik](https://user-images.githubusercontent.com/48821826/115829676-8c492280-a40f-11eb-9446-2172d99658d6.png)


Moreover an error occurs when checking the "CtrAHUBasic" (used in example "GenericAHU" and "EONERC_AHU2"):
![grafik](https://user-images.githubusercontent.com/48821826/115829258-10e77100-a40f-11eb-9199-1e1233d77ac3.png)

2021-05-04 15:39 UTC, FelixStege requested changes
-  Checking the model AixLib.Systems.ModularAHU.RegisterModule produces errors
![RegisterModule](https://user-images.githubusercontent.com/38731996/116987849-db286f00-accf-11eb-9f31-e25ab9651f53.PNG)

- Simulation of AixLib.Systems.ModularAHU.Examples.GenericAHU and AixLib.Systems.ModularAHU.Examples.EONERC_AHU2 produces warnings:
![GenericAHU](https://user-images.githubusercontent.com/38731996/117024416-425b1900-acfa-11eb-8aa1-a03272ba36d1.PNG)

- Simulation of AixLib.Systems.ModularAHU.Validation.AHU2_Cooler, AHU2_Heater and AHU2_Preheater shows a warning, which can be removed by adding a constant boolean signal
![AHU2_Cooler](https://user-images.githubusercontent.com/38731996/117026320-f7420580-acfb-11eb-9720-c5ceffdfd6cb.PNG)

2021-05-04 15:39 UTC, FelixStege commented on AixLib/Systems/ModularAHU/Examples/EONERC_AHU2.mo
> +  Fluid.Sources.Boundary_pT SinkSink(
sinkCooler

2021-05-04 15:39 UTC, FelixStege commented on AixLib/Systems/ModularAHU/Examples/GenericAHU.mo
> +  Fluid.Sources.Boundary_pT SinkSink(
sinkCooler

2021-05-04 15:39 UTC, FelixStege commented on AixLib/Systems/ModularAHU/Examples/GenericAHU.mo
> +    energyDynamics=Modelica.Fluid.Types.Dynamics.FixedInitial,
setting massDynamics the same way removes the initial value warnings

2021-05-04 15:39 UTC, FelixStege commented on AixLib/Systems/ModularAHU/Examples/EONERC_AHU2.mo
> +    energyDynamics=Modelica.Fluid.Types.Dynamics.FixedInitial,
setting massDynamics the same way removes the initial value warnings

2021-05-06 18:54 UTC, alexanderAKU commented on AixLib/Systems/ModularAHU/GenericAHU.mo
> +    "Nominal mass flow rate in hydraulics";
min modifier deltetd

2021-05-06 18:55 UTC, alexanderAKU commented on AixLib/Systems/ModularAHU/GenericAHU.mo
> +  RegisterModule perheater(
done

2021-05-06 19:59 UTC, alexanderAKU commented on AixLib/Systems/ModularAHU/Controller/CtrAHUBasic.mo
> +    "PID controller for retrun fan. Is deactivated if useTwoFanCtr is false."
done

2021-05-06 20:00 UTC, alexanderAKU commented on AixLib/Systems/ModularAHU/BaseClasses/GenericAHUBus.mo
> +  SI.Temperature TExhAirMea "Return air temperature";
done

2021-05-06 20:03 UTC, alexanderAKU commented on AixLib/Systems/ModularAHU/Examples/EONERC_AHU2.mo
> +  Fluid.Sources.Boundary_pT SinkSink(
done

2021-05-06 20:03 UTC, alexanderAKU commented on AixLib/Systems/ModularAHU/Examples/GenericAHU.mo
> +  Fluid.Sources.Boundary_pT SinkSink(
done

2021-05-06 20:25 UTC, alexanderAKU commented on AixLib/Systems/ModularAHU/Examples/GenericAHU.mo
> +    energyDynamics=Modelica.Fluid.Types.Dynamics.FixedInitial,
done

2021-05-10 12:45 UTC, alexanderAKU commented on AixLib/Systems/ModularAHU/Examples/EONERC_AHU2.mo
> +    energyDynamics=Modelica.Fluid.Types.Dynamics.FixedInitial,
Done

2022-02-07 16:14 UTC, KremerMartin approved these changes

2022-02-07 16:23 UTC, FelixStege approved these changes

2022-02-07 16:29 UTC, merged