Update html_tidy_errors.py script and WhiteList
RWTH-EBC/AixLib pull request #1043
Opened 2020-11-03 10:27 UTC by SvenHinrichs

Corrects the bugs from the script html_tidy_errors.py and updates the whiteList.

2020-11-03 11:18 UTC, DaJansenGit requested changes

2020-11-03 11:18 UTC, DaJansenGit commented on bin/03_WhiteLists/HTML_IBPSA_WhiteList.txt
> -IBPSA.Media.Steam.mo
is this wanted?

2020-11-03 11:18 UTC, DaJansenGit commented on bin/03_WhiteLists/HTML_IBPSA_WhiteList.txt
> -IBPSA.Media.Examples.SteamDerivativeCheck.mo
the lines 1680-1686 also wanted?

2020-11-03 11:44 UTC, SvenHinrichs commented on bin/03_WhiteLists/HTML_IBPSA_WhiteList.txt
> -IBPSA.Media.Examples.SteamDerivativeCheck.mo
This is correct because IBPSA has made changes in the media package. These models no longer exist there with this name. (https://github.com/ibpsa/modelica-ibpsa/tree/master/IBPSA/Media)

2020-11-03 16:12 UTC, DaJansenGit approved these changes

2020-11-04 08:05 UTC, DaJansenGit requested changes
Due to the discussion of accepting both, <br/> and <br /> as valid html, I would suggest to change this first and perform the merge request afterwards.

2020-11-05 08:44 UTC, DaJansenGit requested changes

2020-11-05 08:44 UTC, DaJansenGit commented on bin/02_CITests/SyntaxTests/html_tidy_errors.py
> +						print("LINES*************************************")
check this

2020-11-05 08:44 UTC, DaJansenGit commented on bin/02_CITests/SyntaxTests/html_tidy_errors.py
> +						print(lines)
this also?

2020-11-16 12:10 UTC, DaJansenGit approved these changes

2020-11-16 12:47 UTC, merged