#403 new dhc pipe integration into dev
RWTH-EBC/AixLib pull request #1078
Opened 2021-02-08 17:27 UTC by MichaMans

This adds the more universal DHC pipe for DHC simulations

2021-02-16 15:16 UTC, TobiasBlacha requested changes

2021-02-16 15:16 UTC, TobiasBlacha commented on AixLib/Fluid/DistrictHeatingCooling/Pipes/Examples/DHCPipe.mo
> +  \"modelica://AixLib.Fluid.DistrictHeatingCooling.Pipes.PlugFlowPipeZeta\">
```suggestion
  \"modelica://AixLib.Fluid.DistrictHeatingCooling.Pipes.DHCPipe\">
```

2021-02-16 15:16 UTC, TobiasBlacha commented on AixLib/Fluid/DistrictHeatingCooling/Pipes/Examples/DHCPipe.mo
> +  AixLib.Fluid.DistrictHeatingCooling.Pipes.PlugFlowPipeZeta</a>. This
```suggestion
  AixLib.Fluid.DistrictHeatingCooling.Pipes.DHCPipe</a>. This
```

2021-02-16 15:16 UTC, TobiasBlacha commented on AixLib/Fluid/DistrictHeatingCooling/Pipes/Examples/DHCPipe.mo
> +  <li>September 25, 2019 by Nils Neuland:<br/>
```suggestion
   <li>November 12, 2020, by Michael Mans:<br/>
```

2021-02-16 15:16 UTC, TobiasBlacha commented on AixLib/Fluid/DistrictHeatingCooling/Pipes/Examples/DHCPipe.mo
> +    __Dymola_Commands(file="modelica://AixLib/Resources/Scripts/Dymola/Fluid/DistrictHeatingCooling/Pipes/Examples/PlugFlowPipeZeta.mos"
```suggestion
```

2021-02-16 15:16 UTC, TobiasBlacha commented on AixLib/Fluid/DistrictHeatingCooling/Pipes/Examples/DHCPipe.mo
> +                      "Simulate and plot"),
```suggestion
```

2021-02-16 15:16 UTC, TobiasBlacha commented on AixLib/Fluid/DistrictHeatingCooling/Pipes/Examples/DHCPipe.mo
> +    experiment(StopTime=1000, Tolerance=1e-006),
```suggestion
```

2021-02-16 15:16 UTC, TobiasBlacha commented on AixLib/Fluid/DistrictHeatingCooling/Pipes/Examples/DHCPipe.mo
> +model DHCPipe "Simple example of PlugFlowPipe"
```suggestion
model DHCPipe "Simple example of DHCPipe and its four different modes"
```

2021-02-16 15:16 UTC, TobiasBlacha commented on AixLib/Fluid/DistrictHeatingCooling/Pipes/Examples/DHCPipe.mo
> +  rate.
```suggestion
  rate. All four possible applications of the DHC pipe model are shown as examples.
```

2021-02-16 15:16 UTC, TobiasBlacha commented on AixLib/Fluid/DistrictHeatingCooling/Pipes/DHCPipe.mo
> +    final rho=rhoSoi,
```suggestion
    final rho=rho_soi,
```

2021-02-16 15:16 UTC, TobiasBlacha commented on AixLib/Fluid/DistrictHeatingCooling/Pipes/DHCPipe.mo
> +    final rho=rhoSoi,
```suggestion
    final rho=rho_soi,
```

2021-02-16 15:16 UTC, TobiasBlacha commented on AixLib/Fluid/DistrictHeatingCooling/Pipes/DHCPipe.mo
> +    final rho=rhoSoi,
```suggestion
    final rho=rho_soi,
```

2021-02-16 15:16 UTC, TobiasBlacha commented on AixLib/Fluid/DistrictHeatingCooling/Pipes/DHCPipe.mo
> +    final d_out=d_in + thickness_ground/3,
```suggestion
    final d_out=d_in + thickness_soi/3,
```

2021-02-16 15:16 UTC, TobiasBlacha commented on AixLib/Fluid/DistrictHeatingCooling/Pipes/DHCPipe.mo
> +    final d_in=dh + 2*thickness + thickness_ground/3,
```suggestion
    final d_in=dh + 2*thickness + thickness_soi/3,
```

2021-02-16 15:16 UTC, TobiasBlacha commented on AixLib/Fluid/DistrictHeatingCooling/Pipes/DHCPipe.mo
> +    final d_in=dh + 2*thickness + 2*thickness_ground/3,
```suggestion
    final d_in=dh + 2*thickness + 2*thickness_soi/3,
```

2021-02-17 10:09 UTC, TobiasBlacha approved these changes

2021-02-26 12:23 UTC, MichaMans commented
@TobiasBlacha could you have a quick look again and maybe approve it? Checks are now passing

2021-02-26 12:43 UTC, TobiasBlacha approved these changes

2021-02-26 12:52 UTC, merged