HOM project
RWTH-EBC/AixLib pull request #1091
Opened 2021-03-11 11:16 UTC by PMehrfeld

Finally, after appr. 1 year of development, this branch can be merged into development.

The main changes are:
- Partial room model
- Much better propagation from wall level to building level for OFD rooms and building
- Comparative validation according to ASHRAE
- Empirical validation on the basis of two measurement references

2021-03-15 09:16 UTC, FWuellhorst requested changes
Nice work! I haven't looked at all Resources and HOM files as it is just too much and you did internal reviews beforehand.
Besides the conversion error and some open questions, I have no requests.

2021-03-15 09:16 UTC, FWuellhorst commented on AixLib/Resources/Scripts/ConvertAixLib_from_0.11.2_to_0.11.3.mos
> +convertModifiers("AixLib.ThermalZones.HighOrder.Components.Walls.Wall", "solarDistribution",  fill("",0));
I get the following error:
```
Argument number 2, oldElements = "solarDistribution", in
convertModifiers("AixLib.ThermalZones.HighOrder.Components.Walls.Wall", "solarDistribution", fill("", 0), false)
must be a vector.
```

2021-03-15 09:16 UTC, FWuellhorst commented on AixLib/package.mo
> +    version="0.11.2", script="modelica://AixLib/Resources/Scripts/ConvertAixLib_from_0.11.2_to_0.11.3.mos")),
Why increase the numbers three times in comparison to dev?

2021-03-15 09:16 UTC, FWuellhorst commented on AixLib/ThermalZones/HighOrder/House/MFD/BuildingEnvelope/OneAppartment_VoWo.mo
> +  replaceable model CorrSolarGainWin = AixLib.ThermalZones.HighOrder.Components.WindowsDoors.BaseClasses.CorrectionSolarGain.PartialCorG
All models in `AixLib.ThermalZones.HighOrder.Rooms.MFD` don't use the partial room model! Is this on purpose?

2021-03-15 09:16 UTC, FWuellhorst commented on AixLib/ThermalZones/HighOrder/Rooms/BaseClasses/PartialRoom.mo
> +
I was wondering if another `PartialRoom`, `PartialRoomFourWalls` would have been an option as all examples have at least 4 walls, a floor and a ceiling. 
This would also make sense as the record already contains the information on these wall types.
However, this might be something for future developments.

2021-03-15 16:25 UTC, PMehrfeld commented on AixLib/Fluid/Actuators/package.mo
> +
Solved in 219b06181c81a537470463072a783f68d1139cf7

2021-03-15 16:33 UTC, PMehrfeld commented on AixLib/Obsolete/Year2020/ThermalZones/HighOrder/Rooms/MFD/CellarAttic/Attic_Ro2Lf1.mo
> +within AixLib.Obsolete.Year2020.ThermalZones.HighOrder.Rooms.MFD.CellarAttic;
Only the classes for cellar and attic of the MFH were moved, since they are not in use in any direct AixLib example.

2021-03-15 16:35 UTC, PMehrfeld commented on AixLib/ThermalZones/HighOrder/Rooms/BaseClasses/PartialRoom.mo
> +
I agree. However, having such a base class with ceiling, floor and 4 walls can still be added in a further issue.

2021-03-16 06:30 UTC, PMehrfeld commented on AixLib/Fluid/Examples/GeothermalHeatPump/BaseClasses/GeothermalHeatPumpBase.mo
> +    tableHeatFlowCondenser=[0,266.16,275.15,280.15,283.15,293.15; 308.15,9700,11600,13000,14800,16300; 323.15,10000,11200,12900,16700,17500]) "Base load energy conversion unit" annotation (Placement(
Will be solved in #1093.

2021-03-18 12:01 UTC, PMehrfeld commented on AixLib/DataBase/Walls/Collections/EmpricalValidation/Building1.mo
> +record Building1
(Hopefully) solved in 42109219567f1722f8a35decaebed91ec48892c0. Needs to be checked if CI finishes successfully.

2021-03-18 12:02 UTC, PMehrfeld commented on AixLib/DataBase/Walls/Collections/EmpricalValidation/Building1.mo
> +record Building1
Due to historic development of this example of emp. validation, the use case was still named Building1. However, Warehouse is the new and more precise use-case name now.

2021-03-18 12:11 UTC, PMehrfeld commented on AixLib/Resources/Scripts/ConvertAixLib_from_0.11.2_to_0.11.3.mos
> +convertModifiers("AixLib.ThermalZones.HighOrder.Components.Walls.Wall", "solarDistribution",  fill("",0));
Solved in 8ea49cd054a2b167f2e10c1ad7e0437ec49774c7

2021-03-18 12:15 UTC, PMehrfeld commented on AixLib/package.mo
> +    version="0.11.2", script="modelica://AixLib/Resources/Scripts/ConvertAixLib_from_0.11.2_to_0.11.3.mos")),
Your are right. Was due to various sub-branches within the HOM project. Resolved in 201422ebd4e6644a8ec582a7c315a5a8d864b5fc

2021-03-18 12:27 UTC, PMehrfeld commented on AixLib/DataBase/ThermalZones/ZoneRecordDummy.mo
> +    maxIrr=fill(0, nOrientations),
To be honest, I am not sure. I assume one of the contributors added it due to a check error.  
I have noticed that it is included in the `development` branch in the `ZoneBaseRecord` ([link to line](https://github.com/RWTH-EBC/AixLib/blob/development/AixLib/DataBase/ThermalZones/ZoneBaseRecord.mo#L101)) but not in the `ZoneRecordDummy` ([link to line](https://github.com/RWTH-EBC/AixLib/blob/development/AixLib/DataBase/ThermalZones/ZoneRecordDummy.mo#L74)). 

Thus, I think this is a good addition and I would just leave it here in this PR.

2021-03-18 12:33 UTC, PMehrfeld commented on AixLib/DataBase/WindowsDoors/Simple/WindowSimple_EnEV2009.mo
> -  extends OWBaseDataDefinition_Simple(Uw = 1.3, g = 0.6, Emissivity = 0.9, frameFraction = 0.2);
It has not directly to do with the capacity. But yes, the simple window, does not have an emissivity factor for shortwave radiation (see `AixLib.ThermalZones.HighOrder.Components.WindowsDoors.WindowSimple`). Instead, it includes a correction model (`AixLib.ThermalZones.HighOrder.Components.WindowsDoors.BaseClasses.CorrectionSolarGain.PartialCorG`) which transforms (solar) shortwave radiation into a heat flow for the node that represents the mean (longwave) radiant temperature. Therefore, we deleted the factor `Emissivity` from the base record `AixLib.DataBase.WindowsDoors.Simple.OWBaseDataDefinition_Simple`.

2021-03-18 12:35 UTC, PMehrfeld commented on AixLib/ThermalZones/HighOrder/House/MFD/BuildingEnvelope/OneAppartment_VoWo.mo
> +  replaceable model CorrSolarGainWin = AixLib.ThermalZones.HighOrder.Components.WindowsDoors.BaseClasses.CorrectionSolarGain.PartialCorG
Absolutely! I admit that I wanted to do this still in this branch. However, I already raised an issue #978. So we can solve this after this PR from `development` as basis.

2021-03-18 12:38 UTC, PMehrfeld commented
@FWuellhorst: I addressed all your comments. Thanks a lot! They were quite good and helpful. Thus, I re-requested your review. 

If the CI pipelines finish successfully and you approve the review, you (or I) can merge and delete the branch `HOM_project`.

2021-03-18 12:48 UTC, FWuellhorst approved these changes
Nice work! Besides my last question, everything looks fine to me :) As you know more about these scripts, I will approve anyways. You can check if it needs a fix. 

I will also leave you the honours to merge and delete the branch ;)

2021-03-18 12:48 UTC, FWuellhorst commented on AixLib/Resources/Scripts/ConvertAixLib_from_0.10.5_to_0.11.0.mos
> +convertClass("AixLib.ThermalZones.HighOrder.Components.WindowsDoors.BaseClasses.CorrectionSolarGain.NoCorG", "AixLib.ThermalZones.HighOrder.Components.WindowsDoors.BaseClasses.CorrectionSolarGain.Cor
One last thing, shouldn't this conversion script go from 0.10.5 to 0.10.6 or 0.10.7?

2021-03-18 12:54 UTC, PMehrfeld commented on AixLib/Resources/Scripts/ConvertAixLib_from_0.10.5_to_0.11.0.mos
> +convertClass("AixLib.ThermalZones.HighOrder.Components.WindowsDoors.BaseClasses.CorrectionSolarGain.NoCorG", "AixLib.ThermalZones.HighOrder.Components.WindowsDoors.BaseClasses.CorrectionSolarGain.Cor
Good eye ;) Solved in eafec7023aba1c8f648ac7a42b9a8c85a60ae734

2021-03-18 13:25 UTC, FWuellhorst approved these changes
Everything looks good!

2021-03-18 19:00 UTC, merged