Issue1092 new hp per data
RWTH-EBC/AixLib pull request #1109
Opened 2021-05-05 11:32 UTC by FWuellhorst

Fix issues #912, #1092 and #1093.

Besides, add a HeatingRod model and introduce `each` in Storage model.

2021-05-17 14:43 UTC, LauraMaier requested changes

2021-05-17 14:43 UTC, LauraMaier commented on AixLib/DataBase/HeatPump/PerformanceData/BaseClasses.mo
>      parameter Real scalingFactor=1 "Scaling factor of heat pump";
Why is this parameter protected?

2021-05-17 14:43 UTC, LauraMaier commented on AixLib/DataBase/HeatPump/PerformanceData/LookUpTable2D.mo
>      Line(points={{0.0,40.0},{0.0,-40.0}}),
Update Revision!

2021-05-17 14:43 UTC, LauraMaier commented on AixLib/DataBase/HeatPump/PerformanceData/LookUpTableND.mo
>      Line(points={{0.0,40.0},{0.0,-40.0}}),
Something went wrong with the revision part of the documentation. Please revise it so that an extra section is created

2021-05-17 14:43 UTC, LauraMaier commented on AixLib/DataBase/HeatPump/PerformanceData/LookUpTableND.mo
> -          -30},{42,-30},{42,-48}},
General comment: graphical view looks a bit messy. Please tidy up a bit :-)

2021-05-17 14:43 UTC, LauraMaier commented on AixLib/DataBase/HeatPump/PerformanceData/PolynomalApproach.mo
>            lineColor={0,0,255},
Again, please update Revision section

2021-05-17 14:43 UTC, LauraMaier commented on AixLib/DataBase/HeatPump/PerformanceData/VCLibMap.mo
> +model VCLibMap
Why didn't you use the full name vapour compression like in the heat pump bus?

2021-05-17 14:43 UTC, LauraMaier commented on AixLib/DataBase/HeatPump/PerformanceData/VCLibMap.mo
> +  "Multi-dimensional performance map encompasing choices of fluid and flowsheet based on steady state calculations using the Vapor Compression Library"
Also: where can I find THE Vapor Compression Lib? Maybe add some more information in the documentation section

2021-05-17 14:43 UTC, LauraMaier commented on AixLib/Fluid/Examples/GeothermalHeatPump/BaseClasses/GeothermalHeatPumpBase.mo
> +  //  "Initial temperature of high temperature components";
I would suggest to just delete this, right?

2021-05-17 14:43 UTC, LauraMaier commented on AixLib/Fluid/Examples/GeothermalHeatPump/BaseClasses/GeothermalHeatPumpBase.mo
>    Storage.Storage coldStorage(
Why didn't we use the model `AixLib.Fluid.Storage.BufferStorage`?

2021-05-17 14:43 UTC, LauraMaier commented on AixLib/Fluid/Examples/GeothermalHeatPump/BaseClasses/GeothermalHeatPumpBase.mo
> +  parameter Modelica.SIunits.Temperature T_start_warm = 300
better use hot instead of warm due to consistency reasons?

2021-05-17 14:43 UTC, LauraMaier commented on AixLib/Fluid/Examples/GeothermalHeatPump/BaseClasses/GeothermalHeatPumpBase.mo
> +    m_flow_nominal_HE=0.5,
Wouldn't it be nicer to declare this as a general parameter for the whole model?

2021-05-21 06:10 UTC, FWuellhorst commented on AixLib/Controls/HeatPump/Examples/HeatPumpController.mo
> +  connect(heatPumpControlBus.nSet, showN.numberPort) annotation (Line(
Yes, as discussed: This is the set point signal for the HP. If applications require both signals, future versions could introduce `nMea` as well.

2021-05-21 06:14 UTC, FWuellhorst commented on AixLib/Controls/HeatPump/Examples/HeatPumpController.mo
>      annotation (Placement(transformation(extent={{66,40},{86,60}})));
I will try my best :) This was an old example related to GoethermalHeatPump.

2021-05-21 06:18 UTC, FWuellhorst commented on AixLib/Fluid/HeatExchangers/HeatingRod.mo
> +  parameter Real eta=0.97 "Efficiency of the heating rod";
For the volume? Because it aligns with the modelling approach of the IBPSA. 
If you mean the efficiency, i can remove it.

2021-05-21 06:24 UTC, FWuellhorst commented on AixLib/Controls/Interfaces/VapourCompressionMachineControlBus.mo
> +  Real iceFacMea(start=1)
Yes and now. We set the iceFac using a model for the icing, not a controller. Thus I see the icingFactor as a measurement of the device and not some sort of setpoint. But I agree, this is confusing. I think a possible enhancement to the model would be to include all internal safety controls in the model HeatPump it self. This way it would be analog to a real device.

2021-05-21 06:30 UTC, FWuellhorst commented on AixLib/DataBase/HeatPump/PerformanceData/BaseClasses.mo
>      parameter Real scalingFactor=1 "Scaling factor of heat pump";
Because we overwrite the parameter from the HeatPump or Chiller model. The user should not be able to set two different scalingFactors.

2021-05-21 07:54 UTC, FWuellhorst commented on AixLib/DataBase/HeatPump/PerformanceData/VCLibMap.mo
> +model VCLibMap
Because the library is called VCLib.

2021-05-21 07:55 UTC, FWuellhorst commented on AixLib/DataBase/HeatPump/PerformanceData/VCLibMap.mo
> +  "Multi-dimensional performance map encompasing choices of fluid and flowsheet based on steady state calculations using the Vapor Compression Library"
To be published. Currently, Christian waits for review by the Modelica Conference. Journal is planned.

2021-05-21 07:58 UTC, FWuellhorst commented on AixLib/Fluid/Examples/GeothermalHeatPump/BaseClasses/GeothermalHeatPumpBase.mo
>    Storage.Storage coldStorage(
Good question. I just updated the model from Marc with the goal of only changing the heat pump.

2021-05-21 10:37 UTC, FWuellhorst commented on AixLib/Fluid/HeatExchangers/Examples/HeatingRod.mo
> +    Q_flow_nominal=10*Q_flow_nominal)
The whole example is duplicated based on the IBPSA WaterCooler_u. Changing Q_flow_nominal would change other parameters as well :/

2021-05-21 10:38 UTC, FWuellhorst commented on AixLib/Resources/Scripts/Dymola/Fluid/HeatExchangers/Examples/HeatingRod.mos
> +simulateModel("AixLib.Fluid.HeatExchangers.Examples.HeatingRod", stopTime=172800, method="Radau", tolerance=1e-6, resultFile="HeatingRod");
I copied the file from the IBPSA script, actually no idea why.

2021-05-21 11:05 UTC, FWuellhorst commented on AixLib/Controls/HeatPump/SafetyControls/AntiFreeze.mo
> +  connect(sigBusHP.TConInMea, min.u1) annotation (Line(
This is due to old or other models from Marc or Mirko. 
If I see it i will refactor it, however this is a separate issue / pr :)

2021-05-21 11:06 UTC, FWuellhorst commented on AixLib/Controls/HeatPump/SafetyControls/OnOffControl.mo
> +within AixLib.Controls.HeatPump.SafetyControls;
Yes, it's confusing. As I named the model in my Modelica Conference Paper the same I would like to keep the name for now. But we can easily refactor it in the future!

2021-05-21 11:07 UTC, FWuellhorst commented on AixLib/Resources/ReferenceResults/Dymola/AixLib_Fluid_HeatPumps_Examples_HeatPump.txt
>  }
Yes, that could be! The examples still look fine, I will update the reference results!

2021-05-21 14:03 UTC, LauraMaier commented on AixLib/Controls/HeatPump/SafetyControls/OnOffControl.mo
> +within AixLib.Controls.HeatPump.SafetyControls;
Ok, can you address this in an issue maybe for future enhancement?

2021-05-21 14:04 UTC, LauraMaier commented on AixLib/Fluid/HeatExchangers/HeatingRod.mo
> +  parameter Real eta=0.97 "Efficiency of the heating rod";
Yes, I meant the efficiency :D

2021-05-21 14:05 UTC, LauraMaier commented on AixLib/DataBase/HeatPump/PerformanceData/VCLibMap.mo
> +  "Multi-dimensional performance map encompasing choices of fluid and flowsheet based on steady state calculations using the Vapor Compression Library"
ok please addres this in an issue and link the VC Lib within the Docs as soon as available open-source :-)

2021-05-21 14:06 UTC, LauraMaier commented on AixLib/Fluid/Examples/GeothermalHeatPump/BaseClasses/GeothermalHeatPumpBase.mo
>    Storage.Storage coldStorage(
ok, again: maybe we address this in a separate issue?

2021-05-21 14:07 UTC, LauraMaier approved these changes

2021-05-21 14:47 UTC, FWuellhorst commented on AixLib/Fluid/Examples/GeothermalHeatPump/BaseClasses/GeothermalHeatPumpBase.mo
>    Storage.Storage coldStorage(
Yes - see: https://github.com/RWTH-EBC/AixLib/issues/1127

2021-05-21 14:51 UTC, FWuellhorst commented on AixLib/Controls/HeatPump/SafetyControls/OnOffControl.mo
> +within AixLib.Controls.HeatPump.SafetyControls;
Yes, see: https://github.com/RWTH-EBC/AixLib/issues/1128

2021-05-27 06:31 UTC, LauraMaier approved these changes

2021-05-27 06:32 UTC, merged