Issue 1188 Add simulate and plot scripts for ROM examples
RWTH-EBC/AixLib pull request #1189
Opened 2021-10-29 11:28 UTC by larissakuehn

Added missing simulate and plot scripts for all ROM examples

2021-10-31 08:14 UTC, LauraMaier approved these changes

2024-07-17 06:55 UTC, FWuellhorst requested changes
@larissakuehn If you participate in the hackday, here are some open points. If not, I can take care of them. In any case #1506 should be merged before this one

2024-07-17 06:55 UTC, FWuellhorst commented on AixLib/Resources/Scripts/Dymola/ThermalZones/ReducedOrder/Examples/Multizone.mos
> +simulateModel("AixLib.ThermalZones.ReducedOrder.Examples.Multizone", tolerance=1e-6, stopTime=3.1536e+007, numberOfIntervals=0, outputInterval=3600, method="Radau", resultFile="Multizone");
Can we add TDryBul to show how the outdoor air temperature affects the room temperature?

2024-07-17 06:55 UTC, FWuellhorst commented on AixLib/Resources/Scripts/Dymola/ThermalZones/ReducedOrder/Examples/MultizonePartlyCooled.mos
> +createPlot(id = 1,
Here, PHeater / PCooler would be better instead of just the static air temperature?

2024-07-17 06:55 UTC, FWuellhorst commented on AixLib/ThermalZones/ReducedOrder/Examples/Multizone.mo
> +    __Dymola_Commands(file=
I know the other examples also use full year specs, but we could choose to go for maybe a week or month in this PR, as this impacts CI runtime and users will still learn how the model works.

2024-07-19 16:22 UTC, FWuellhorst approved these changes

2024-07-19 16:22 UTC, merged