Issue1122 air exchange boolean
RWTH-EBC/AixLib pull request #1190
Opened 2021-10-29 12:15 UTC by larissakuehn

Issue #1122 is solved by replacing use_AirExchange by two booleans: 
- use_NaturalAirExchange
- use_MechanicalAirExchange

2022-06-09 05:46 UTC, FWuellhorst requested changes
Thanks for the PR! Prior to a functional check, some style changes :)

2022-06-09 05:46 UTC, FWuellhorst commented on AixLib/ThermalZones/ReducedOrder/Multizone/BaseClasses/PartialMultizone.mo
> +    "Consider mechanical ventilation infiltration by setting true";
Remove "infiltration"

2022-06-09 05:46 UTC, FWuellhorst commented on AixLib/package.mo
> +    version= "1.0.3",
New version 1.0.4 is missing in the version specifier above these conversion files

2022-06-09 05:46 UTC, FWuellhorst commented on AixLib/ThermalZones/ReducedOrder/ThermalZone/ThermalZone.mo
> +within AixLib.ThermalZones.ReducedOrder.ThermalZone;
Is the style check currently skipped? It seems like this file has a lot of style related changes

2022-06-09 05:46 UTC, FWuellhorst commented on AixLib/ThermalZones/ReducedOrder/ThermalZone/ThermalZone.mo
> +    AixLib.ThermalZones.ReducedOrder.SolarGain.BaseClasses.PartialCorrectionG
remove

2022-06-09 05:46 UTC, FWuellhorst commented on AixLib/ThermalZones/ReducedOrder/ThermalZone/ThermalZone.mo
> + parameter Boolean use_MechanicalAirExchange = false
indent

2022-06-09 05:46 UTC, FWuellhorst commented on AixLib/ThermalZones/ReducedOrder/ThermalZone/ThermalZone.mo
> +// connect(airExcMoi.ventRate, addInfVen.y) annotation (Line(points={{-21.2,
remove if not required

2022-06-09 05:46 UTC, FWuellhorst commented on AixLib/ThermalZones/ReducedOrder/ThermalZone/ThermalZone.mo
> +>>>>>>>>> Temporary merge branch 2
remove

2022-06-09 07:38 UTC, larissakuehn commented on AixLib/ThermalZones/ReducedOrder/Multizone/BaseClasses/PartialMultizone.mo
> +    "Consider mechanical ventilation infiltration by setting true";
I changed description of use_NaturalAirExchgange to "Consider natural infiltration and ventilation by setting true" and of use_MechanicalAirExchange to "Consider mechanical ventilation by setting true" within ThermalZone and PartialMultizone

2022-06-13 08:03 UTC, FWuellhorst approved these changes
Everything looks good! Thanks for the nice work :)

2022-06-13 08:17 UTC, merged