Issue1171 storage spring cleaning
RWTH-EBC/AixLib pull request #1226
Opened 2022-01-28 07:08 UTC by LauraMaier

This closes issue #1171

2022-01-28 07:18 UTC, FWuellhorst requested changes
Nice work! Remove TABS changes and check comments.

2022-01-28 07:18 UTC, FWuellhorst commented on AixLib/Fluid/Storage/StorageDetailed.mo
> +    DataBase.Storage.BufferStorageBaseDataDefinition                                                                                         "Data record for Storage"
Should this record then be called "DetailedStorageBaseDataDefinition"?

2022-01-28 07:18 UTC, FWuellhorst commented on AixLib/Fluid/Storage/StorageDetailed.mo
> +        iconTransformation(extent={{-88,20},{-74,32}})));
Why move this HC1 port to the code part above HC1 comment?

2022-01-28 07:18 UTC, FWuellhorst commented on AixLib/Resources/Scripts/ConvertAixLib_from_1.0.2_to_1.0.3.mos
> +convertClass("AixLib.Fluid.Storage.BufferStorage", "AixLib.Fluid.Storage.StorageDetailed");
If you accept the name changes above, add the conversion here.

2022-01-28 07:18 UTC, FWuellhorst commented on AixLib/Systems/TABS/BaseClasses/TabsBus.mo
> +</p>
Why did you change all these TABS models?

2022-01-28 08:06 UTC, LauraMaier commented on AixLib/Fluid/Storage/StorageDetailed.mo
> +    DataBase.Storage.BufferStorageBaseDataDefinition                                                                                         "Data record for Storage"
Good idea, changed it in the latest push

2022-01-28 08:07 UTC, LauraMaier commented on AixLib/Resources/Scripts/ConvertAixLib_from_1.0.2_to_1.0.3.mos
> +convertClass("AixLib.Fluid.Storage.BufferStorage", "AixLib.Fluid.Storage.StorageDetailed");
Added conversion in latest push

2022-01-28 08:10 UTC, LauraMaier commented on AixLib/Systems/TABS/BaseClasses/TabsBus.mo
> +</p>
Automatic CI merge

2022-01-28 08:11 UTC, LauraMaier commented on AixLib/Systems/TABS/BaseClasses/TabsBus.mo
> +</p>
Automatic CI merge...

2022-01-28 08:19 UTC, LauraMaier commented on AixLib/Fluid/Storage/StorageDetailed.mo
> +        iconTransformation(extent={{-88,20},{-74,32}})));
Good question, rereplaced it back to old position

2022-01-28 08:19 UTC, LauraMaier commented on AixLib/Fluid/Storage/StorageDetailed.mo
> +        iconTransformation(extent={{-88,20},{-74,32}})));
good question - rechanged this

2022-01-28 11:21 UTC, FWuellhorst approved these changes
Nice work. Just the CI now ;)

2022-10-12 14:31 UTC, FWuellhorst commented
@LauraMaier : Could you update the branch to MSL 4.0? Then I will add my review.

2022-10-14 06:23 UTC, FWuellhorst commented
@LauraMaier : Even though the plots dont show, here is the error:
```
*** Warning: Unspecified initial conditions in 'RunScript("Resources/Scripts/Dymola/Fluid/Storage/Examples/StorageSolarCollector.mos");'.
*** Warning: Unspecified initial conditions in 'RunScript("Resources/Scripts/Dymola/Fluid/Storage/Examples/StorageBoiler.mos");'.
```

2022-10-14 18:05 UTC, LauraMaier commented
@FWuellhorst and @DaJansenGit I tried to fix the problem with the initial conditions which led to a CI fail.
However, the pipeline does not do the full check and simply tells me that checks have passed. What do I have to do to actually check if the PR is ready to be merged now?

2022-10-21 16:57 UTC, LauraMaier commented
@FWuellhorst Will you be able to re-review in October? :) That would be great ! :)

2022-10-28 14:25 UTC, FWuellhorst approved these changes
Thanks for this cleaning up! Looks good!

2024-07-18 12:13 UTC, FWuellhorst approved these changes
Thanks for the feature, I will merge this now

2024-07-18 12:14 UTC, merged