Changed TStart for BufferStorage and Storage to an array
RWTH-EBC/AixLib pull request #1305
Opened 2022-07-14 15:01 UTC by tobinfiedler

Also changed the examples for BufferStorage. The changes in Storage are not testet yet.

> Thank you for making a Pull Request to AixLib!

> Please consider these points before submitting:
> - Mention the issue that this Pull Request intends to solve, and briefly describe what the main changes are.
> - Make sure all new code follows our [Modelica Guidelines](https://github.com/RWTH-EBC/AixLib/wiki/Modelica-guidelines)
> - Make sure all new models include documentation as described in the [Documentation Wiki-Page](https://github.com/RWTH-EBC/AixLib/wiki/Documentation) and are demonstrated by suitable examples

> If you know someone who could review your code, please use the *Reviewer* function on the right to ask for a review and also assign the PR to them. If not, no worries, we will find someone for you.

> Thanks again for your PR! You can delete these first lines before submitting your PR.

2022-07-14 17:24 UTC, LauraMaier requested changes

2022-07-14 17:24 UTC, LauraMaier commented on AixLib/Fluid/Storage/BufferStorage.mo
Maybe just use TStart without TStart[1]?

2022-07-14 17:24 UTC, LauraMaier commented on AixLib/Fluid/Storage/BufferStorage.mo
Maybe give a default value --> fill(TStartWall,n) maybe? or fill(293.15,n)?

2022-07-14 17:24 UTC, LauraMaier commented on AixLib/Fluid/Storage/BufferStorage.mo
>  /////////////CONVECTION/////////////////////////////////////////////////////////////////////////////
What happened here?

2022-07-14 17:24 UTC, LauraMaier commented on AixLib/Fluid/Storage/BufferStorage.mo
>      annotation (Placement(transformation(
The Heating rod is discretized, too, so maybe giving the first array entry is a bit random?

2022-07-14 17:24 UTC, LauraMaier commented on AixLib/Fluid/Storage/Examples/BufferStorage.mo
>    Modelica.Thermal.HeatTransfer.Sources.FixedTemperature fixedTemperature(T=283.15)   annotation(Placement(transformation(extent={{-58,4},
Maybe use different initialization temperatures for each layer so that it has an effect? Then we have to update the reference results. Check the wiki for more information or ask me :)

2022-07-14 17:24 UTC, LauraMaier commented on AixLib/Fluid/Storage/Examples/StorageBoiler.mo
>      redeclare AixLib.DataBase.Storage.Generic_New_2000l data(
see comment above

2022-07-14 17:24 UTC, LauraMaier commented on AixLib/Fluid/Storage/Storage.mo
>        color={0,127,255}));
Were these intended changes?

2022-07-14 17:24 UTC, LauraMaier commented on AixLib/Fluid/Storage/Storage.mo
>      each final m_flow_small=m_flow_small_layer_HE,
Maybe we introduce different TStart arrays, one TStart_HE and one TStart?

2022-07-14 17:24 UTC, LauraMaier commented on AixLib/Fluid/Storage/Storage.mo
>    parameter Modelica.Media.Interfaces.Types.AbsolutePressure p_start=Medium.p_default
The path should be: Modelica.Units.SI.Temperature :)

2022-07-14 17:24 UTC, LauraMaier commented on AixLib/Fluid/Storage/Storage.mo
>        color={0,127,255}));
Intended changes?

2022-10-12 14:21 UTC, tosch4 commented
@tobinfiedler reminder

2023-02-13 13:38 UTC, FelixStege commented
@tobinfiedler, @tosch4, any updates on this?

2023-09-19 11:16 UTC, FWuellhorst commented on AixLib/Fluid/Storage/BufferStorage.mo
I used the mean.

2023-09-19 11:18 UTC, FWuellhorst commented on AixLib/Fluid/Storage/BufferStorage.mo
>  /////////////CONVECTION/////////////////////////////////////////////////////////////////////////////
Its nice like this, `n` is defined before `TStart[n]`

2023-09-19 11:20 UTC, FWuellhorst commented on AixLib/Fluid/Storage/Examples/StorageBoiler.mo
>      redeclare AixLib.DataBase.Storage.Generic_New_2000l data(
I used different values in the other example

2023-09-19 11:25 UTC, FWuellhorst commented on AixLib/Fluid/Storage/Storage.mo
>      each final m_flow_small=m_flow_small_layer_HE,
I think this needs another issue. As the parameters disHC1 are not always the same, and the coils itself have scalar start values, this would need further assumptions. If you need this, we can open a separate issue.

2023-09-19 11:29 UTC, FWuellhorst commented on AixLib/Fluid/Storage/Storage.mo
>        color={0,127,255}));
Dymola does not let you change these manually. I fixed the layout so it looks nice now.

2024-07-19 14:57 UTC, FWuellhorst approved these changes
CI works now

2024-07-19 14:57 UTC, merged