Issue1223 new storage examples
RWTH-EBC/AixLib pull request #1307
Opened 2022-07-14 15:16 UTC by LauraMaier

This closes #1223

2022-07-19 08:27 UTC, MZuschlag commented on AixLib/Fluid/Storage/Examples/StorageSimpleExample.mo
> +  Modelica.Blocks.Continuous.LimPID PID_hr(controllerType=Modelica.Blocks.Types.SimpleController.PI,
AixLib.Controls.Continuous.LimPID

2022-07-19 08:28 UTC, MZuschlag commented on AixLib/Fluid/Storage/Examples/StorageSimpleExample.mo
> +  Modelica.Blocks.Continuous.LimPID PID_pump_gen(
AixLib.Controls.Continuous.LimPID

2022-07-19 08:28 UTC, MZuschlag commented on AixLib/Fluid/Storage/Examples/StorageSimpleExample.mo
> +  Modelica.Blocks.Continuous.LimPID PID_pump_gen1(
AixLib.Controls.Continuous.LimPID

2022-07-19 08:48 UTC, MZuschlag commented on AixLib/Fluid/Storage/Examples/StorageSimpleExample.mo
> +  Modelica.Blocks.Continuous.LimPID PID_pump_gen1(
Besser PID_pump_con?

2022-07-19 09:04 UTC, MZuschlag commented on AixLib/Fluid/Storage/Examples/StorageSimpleExample.mo
> +  Modelica.Blocks.Continuous.LimPID PID_pump_gen1(
bei der Pumpe noch einen Widerstand einbauen, damit die Drehzahl realistischer ausfällt

2022-10-12 14:22 UTC, tosch4 commented
@LauraMaier 
please check feedback from Moritz

2022-10-12 21:03 UTC, LauraMaier commented on AixLib/Fluid/Storage/Examples/StorageSimpleExample.mo
> +  Modelica.Blocks.Continuous.LimPID PID_hr(controllerType=Modelica.Blocks.Types.SimpleController.PI,
done :)

2022-10-12 21:03 UTC, LauraMaier commented on AixLib/Fluid/Storage/Examples/StorageSimpleExample.mo
> +  Modelica.Blocks.Continuous.LimPID PID_pump_gen(
done

2022-10-12 21:09 UTC, LauraMaier commented on AixLib/Fluid/Storage/Examples/StorageSimpleExample.mo
> +  Modelica.Blocks.Continuous.LimPID PID_pump_gen1(
done

2022-10-12 21:10 UTC, LauraMaier commented on AixLib/Fluid/Storage/Examples/StorageSimpleExample.mo
> +  Movers.SpeedControlled_y pumpCon(redeclare package Medium = Medium,
done

2022-10-14 18:08 UTC, LauraMaier commented
I removed the review request from @MZuschlag to speed up the process now even though the review so far was very helpful! :-)

2022-10-21 21:30 UTC, LauraMaier commented
@SvenHinrichs Could you please check why the CI is failing? :)

2022-10-22 09:33 UTC, FWuellhorst commented
@LauraMaier : The job for your new examples fail, because all examples have unspecified initial conditions:
```
Generated 350 regression tests.
*** Warning: Unspecified initial conditions in 'RunScript("Resources/Scripts/Dymola/Fluid/Storage/Examples/StorageSimpleExample.mos");'.
*** Warning: Unspecified initial conditions in 'RunScript("Resources/Scripts/Dymola/Fluid/Storage/Examples/StorageSolarCollector.mos");'.
*** Warning: Unspecified initial conditions in 'RunScript("Resources/Scripts/Dymola/Fluid/Storage/Examples/StorageBoiler.mos");'.
Comparison files output by funnel are stored in the directory 'funnel_comp' of size 13.2 MB.
Run 'report' method of class 'Tester' to access a summary of the comparison results.
Number of models with unspecified initial conditions         : 3
Script that runs unit tests had 3 warnings and 0 errors.
See 'simulator-dymola.log' for details.
```
https://git.rwth-aachen.de/EBC/EBC_all/github_ci/AixLib/-/jobs/3006309

Use FixedInitial will probably solve this issue. While at it, the re-generation of e.g. results in thermal zones or systems should not be necessary.
And, which PR comes first? This one or #1226 ?

I will be able to review both in october.

2022-10-25 00:49 UTC, LauraMaier commented
@FWuellhorst CI hats dann auch endlich mal geschafft :D

2022-10-28 14:24 UTC, FWuellhorst approved these changes
Looks good, thanks for your work!

2022-11-11 10:41 UTC, FWuellhorst requested changes
@LauraMaier Thanks for all the work! I reverted some ref-results, as only the date changed, to avoid confusion. 
I left the TABS changes, as it in line with 80 linewidth. 
Please check my comments and suggestions :)

2022-11-11 10:41 UTC, FWuellhorst commented on bin/ci_whitelist/model_whitelist.txt
> +AixLib.Fluid.Storage.StorageDetailed
Is this still required? Why would it be on the white list?

2022-11-11 10:41 UTC, FWuellhorst commented on AixLib/Resources/Scripts/ConvertAixLib_from_1.0.2_to_1.0.3.mos
> +
Why would this be necessary?

2022-11-11 10:41 UTC, FWuellhorst commented on AixLib/Fluid/Storage/Examples/StorageDetailedExample.mo
> -    __Dymola_Commands(file="modelica://AixLib/Resources/Scripts/Dymola/Fluid/Storage/Examples/BufferStorage.mos" "Simulate and plot"),
Revision is missing. Same applies for StorageDetailed. StorageSimple has revisions in the doc section. Move to revision section.

2022-11-11 10:41 UTC, FWuellhorst commented on AixLib/Fluid/Storage/Examples/StorageSimpleExample.mo
> +    layer_HE(each T(start=308.15,fixed=true)),
Missing doc. What happens in the model? Are the storage levels the only interesting thing to plot? If not, please revise the mos script.

2022-11-11 10:41 UTC, FWuellhorst commented on AixLib/Fluid/Storage/Examples/StorageSimpleExample.mo
> +    layer_HE(each T(start=308.15,fixed=true)),
Also, we could use parameters like Q_flow_nominal to set  `k_HE` and `A_HE` to show users how to parameterize the model?

2022-11-11 10:41 UTC, FWuellhorst commented on AixLib/Fluid/Storage/Examples/StorageSimpleExample.mo
> +    layer_HE(each T(start=308.15,fixed=true)),
Aside from that, the model looks nice. Naming guidelines do not apply, but that's up to you if you want to stick with the three letter rule ;)

2022-11-11 10:41 UTC, FWuellhorst commented on AixLib/Fluid/Storage/Examples/StorageSolarCollector.mo
>      redeclare package MediumHC2 = Medium,
Again, revision in doc section. Also, improve the mos script by adding the temperature outputs, like this for instance:
![image](https://user-images.githubusercontent.com/22442514/201322783-34713859-9b3c-4c7e-8b24-6bac3266283f.png)

2022-11-11 10:41 UTC, FWuellhorst commented on AixLib/Resources/Scripts/Dymola/Fluid/Storage/Examples/StorageDetailedExample.mos
>  createPlot(id=1, position={405, 134, 811, 420}, y={"bufferStorage.heatingCoil1.Therm1[4].Q_flow"}, range={0.0, 90000.0, -200.0, 1800.0}, grid=true, filename="BufferStorage.mat", colors={{28,108,200}}
Dont use id 1, 2, 3 etc. Make one subplot, like here:
```
createPlot(id=2, position={75, 70, 1210, 240}, y={"electrical.distribution.batterySimple.PLoad","electrical.distribution.batterySimple.PCharge"}, grid=true, subPlot=1, colors={{28,108,200},{238,46,47}});
createPlot(id=2, position={75, 70, 1210, 240}, y={"hydraulic.distribution.sigBusDistr.TStoDHWTopMea","hydraulic.distribution.sigBusDistr.TStoBufTopMea","hydraulic.generation.sigBusGen.THeaRodMea"}, grid=true, subPlot=2, colors={{28,108,200},{238,46,47},{0,140,72}});
createPlot(id=2, position={75, 70, 1210, 240}, y={"ventilation.generation.TSup.T","ventilation.generation.weaBus.TDryBul","building.buiMeaBus.TZoneMea[1]"}, grid=true, subPlot=3, colors={{28,108,200},{238,46,47},{0,140,72}});
```

2022-11-11 10:41 UTC, FWuellhorst commented on AixLib/Resources/Scripts/Dymola/Fluid/Storage/Examples/StorageBoiler.mos
> +createPlot(id=2, position={104, 0, 742, 420}, y={"hea.Q_flow"}, range={0.0, 90000.0, 25.0, 65.0}, grid=true, filename="StorageBoiler.mat", colors={{28,108,200}}, displayUnits={"W"});
same id is better

2022-11-11 10:41 UTC, FWuellhorst commented on AixLib/Resources/Scripts/Dymola/Fluid/Storage/Examples/StorageSolarCollector.mos
> +createPlot(id=3, position={104, 0, 742, 420}, y={"solarThermal.Irradiation","solarThermal.heater.Q_flow"}, range={0.0, 90000.0, 25.0, 65.0}, grid=true, filename="StorageSolarCollector.mat", colors={{
ok, you show everything I mentioned above. Use same id to avoid confusion.

2022-11-11 10:41 UTC, FWuellhorst commented on AixLib/Resources/Scripts/Dymola/Fluid/Storage/Examples/StorageSimpleExample.mos
> +createPlot(id=1, position={104, 0, 742, 420}, y={"storageSimple.layer[1].T","storageSimple.layer[2].T","storageSimple.layer[3].T"}, grid=true, filename="StorageSimple.mat", colors={{28,108,200},{100,
consider update

2022-11-11 10:41 UTC, FWuellhorst commented on AixLib/Fluid/Storage/Examples/StorageBoiler.mo
>      redeclare package MediumHC2 = Medium,
Same here: Revision. Maybe add one sentence on what happens from a physics point of view.

2022-11-14 19:33 UTC, LauraMaier commented on AixLib/Resources/Scripts/Dymola/Fluid/Storage/Examples/StorageSimpleExample.mos
> +createPlot(id=1, position={104, 0, 742, 420}, y={"storageSimple.layer[1].T","storageSimple.layer[2].T","storageSimple.layer[3].T"}, grid=true, filename="StorageSimple.mat", colors={{28,108,200},{100,
?

2022-11-14 19:40 UTC, LauraMaier commented on AixLib/Resources/Scripts/Dymola/Fluid/Storage/Examples/StorageSolarCollector.mos
> +createPlot(id=3, position={104, 0, 742, 420}, y={"solarThermal.Irradiation","solarThermal.heater.Q_flow"}, range={0.0, 90000.0, 25.0, 65.0}, grid=true, filename="StorageSolarCollector.mat", colors={{
done

2022-11-14 19:40 UTC, LauraMaier commented on AixLib/Resources/Scripts/Dymola/Fluid/Storage/Examples/StorageBoiler.mos
> +createPlot(id=2, position={104, 0, 742, 420}, y={"hea.Q_flow"}, range={0.0, 90000.0, 25.0, 65.0}, grid=true, filename="StorageBoiler.mat", colors={{28,108,200}}, displayUnits={"W"});
done

2022-11-14 19:40 UTC, LauraMaier commented on AixLib/Resources/Scripts/Dymola/Fluid/Storage/Examples/StorageDetailedExample.mos
>  createPlot(id=1, position={405, 134, 811, 420}, y={"bufferStorage.heatingCoil1.Therm1[4].Q_flow"}, range={0.0, 90000.0, -200.0, 1800.0}, grid=true, filename="BufferStorage.mat", colors={{28,108,200}}
done

2022-11-14 19:41 UTC, LauraMaier commented on bin/ci_whitelist/model_whitelist.txt
> +AixLib.Fluid.Storage.StorageDetailed
It has been before. Maybe @DaJansenGit knows about it?

2022-11-14 19:41 UTC, LauraMaier commented on AixLib/Fluid/Storage/StorageSimple.mo
> +  parameter Modelica.Units.SI.ThermalConductance G_middle=2*Modelica.Constants.pi*h/n/(1/(hConIn*d/2) + 1/lambda_ins*log((d/2 + s_ins)/(d/2))
done

2022-11-14 19:41 UTC, LauraMaier commented on AixLib/Fluid/Storage/StorageSimple.mo
> +        origin={102,-80})));
I added an array for both layer and layer HE temperatures

2022-11-14 19:41 UTC, LauraMaier commented on AixLib/Fluid/Storage/StorageSimple.mo
>    parameter Real kappa = 0.4 annotation(Dialog(group = "Bouyancy"));
Adapted

2022-11-14 19:41 UTC, LauraMaier commented on AixLib/DataBase/Storage/StorageDetailedBaseDataDefinition.mo
> +  parameter SI.ThermalConductivity lambdaIns
done

2022-11-14 22:17 UTC, LauraMaier commented on AixLib/Fluid/Storage/StorageSimple.mo
> +  TTopLayer_HE = layer_HE[n].heatPort.T;
It works well like this. I dont see a point in changing it?

2022-11-17 08:02 UTC, FWuellhorst requested changes
@LauraMaier You somehow deleted the renamed files instead of renaming them. Please change this to keep the file history intact.

2022-11-17 08:02 UTC, FWuellhorst commented on AixLib/DataBase/Storage/BufferStorageBaseDataDefinition.mo
> -///////////input parameters////////////
During the revert, you deleted the old file and added the new one. This deleted the git history. Using git rename, the history would still be intact.

2022-11-17 08:02 UTC, FWuellhorst commented on AixLib/Fluid/Storage/StorageSimple.mo
> +  "Simplified multi-layer storage model with volumes as heat exchangers without pressure losses"
During the revert, you deleted the old file and added the new one. This deleted the git history. Using git rename, the history would still be intact.

2022-11-17 08:02 UTC, FWuellhorst commented on AixLib/Resources/Scripts/Dymola/Fluid/Storage/Examples/StorageBoiler.mos
> +createPlot(id=1, position={104, 0, 742, 420}, y={"bufferStorage.layer[10].T","bufferStorage.layer[5].T","bufferStorage.layer[1].T"},
During the revert, you deleted the old file and added the new one. This deleted the git history. Using git rename, the history would still be intact.

2022-11-18 08:40 UTC, FWuellhorst approved these changes
The local rename does not work for me. I guess one has to do it directly in the correct way, as git already had a history on `StorageDetailedBaseDataDefinition` now. 
But I mean it's not that important! 
Thanks for your work. Now let's wait for HTML

2024-07-26 06:25 UTC, FWuellhorst approved these changes

2024-07-26 07:44 UTC, merged