Issue1297 fluid ports hom
RWTH-EBC/AixLib pull request #1334
Opened 2022-09-06 15:33 UTC by larissakuehn

Adding fluid ports to all zones of the OFD (HOM), except of the attic. P

orts are optional to be enabled in existing examples to avoid errors.

2022-09-07 07:37 UTC, FWuellhorst requested changes
Thanks for the feature! Please check my comments :)

2022-09-07 07:37 UTC, FWuellhorst commented on AixLib/ThermalZones/HighOrder/Examples/OFDHeatLoad.mo
> +
Why is it necessary to add the Medium to all examples?

2022-09-07 07:37 UTC, FWuellhorst commented on AixLib/ThermalZones/HighOrder/Examples/RoomGFOw2_DayNightMode.mo
>    connect(tank.ports[1],Pump. port_a) annotation (Line(
This should not have changed.

2022-09-07 07:37 UTC, FWuellhorst commented on AixLib/ThermalZones/HighOrder/House/OFD_MiddleInnerLoadWall/BuildingEnvelope/WholeHouseBuildingEnvelope.mo
> +            {96,-92},{110,-78}})));
Why not 11? I guess it's confusing for externals why the attic is heated but ventilation is not allowed.

2022-09-07 07:37 UTC, FWuellhorst commented on AixLib/ThermalZones/HighOrder/Examples/OFDHeatLoad.mo
> +
I guess the examples don't have to change the Medium. Such changes are ok, but make the git history crowded, leading to longer searches on when and why a model was changed.

2022-09-12 16:24 UTC, larissakuehn commented on AixLib/ThermalZones/HighOrder/Examples/OFDHeatLoad.mo
> +
Before, the medium was set manually for each room within the models GroundFloorBuildingEnvelope and UpperFloorBuildingEnvelope. I just propagaded all mediums to the top level and only inserted a partial medium within the lower level models. But I could set the Medium within WholeHouseBuldingEnvelope and don't change it within the examples?

2022-09-13 06:16 UTC, FWuellhorst commented on AixLib/ThermalZones/HighOrder/Examples/OFDHeatLoad.mo
> +
No, its all fine :)

2022-09-13 06:17 UTC, FWuellhorst approved these changes
Thanks for the changes!!

2022-09-13 06:41 UTC, merged