Open Modelica PR
RWTH-EBC/AixLib pull request #1378
Opened 2022-10-13 15:31 UTC by FWuellhorst

Bundling all changes, we can check CI only once.

2022-10-13 15:41 UTC, FWuellhorst commented
@LauraMaier : We reviewed all changes in the branch anyway. This branch was used to limit the burden on the CI. You can check again if you want to see the OM issues we solved.

2022-10-13 17:11 UTC, LauraMaier commented on AixLib/Fluid/DistrictHeatingCooling/Pipes/PlugFlowPipeEmbedded.mo
>      annotation (Dialog(tab="Initialization"));
unnecessary commit?

2022-10-13 17:11 UTC, LauraMaier commented on AixLib/Fluid/DistrictHeatingCooling/Pipes/PlugFlowPipeZeta.mo
>      redeclare final package Medium = Medium,
reduce space?

2022-10-13 17:12 UTC, LauraMaier commented on AixLib/Fluid/DistrictHeatingCooling/Pipes/PlugFlowPipeZeta.mo
>      final R=R,
why not final?

2022-10-13 17:12 UTC, LauraMaier commented on AixLib/Fluid/DistrictHeatingCooling/Pipes/PlugFlowPipeZeta.mo
>      annotation (Line(points={{-40,20},{-20,20},{-20,0},{-10,0}},
why is there a space here

2022-10-13 17:12 UTC, LauraMaier commented on AixLib/Fluid/DistrictHeatingCooling/Pipes/PlugFlowPipeZeta.mo
>      annotation (Line(points={{-100,0},{-80,0},{-80,-20},{-20,-20},{-20,0},{-10,0}},
same here?

2022-10-13 17:13 UTC, LauraMaier commented on AixLib/Fluid/DistrictHeatingCooling/Pipes/StaticPipe.mo
>      annotation (Dialog(tab="Initialization"));
unnecessary commit?

2022-10-13 17:13 UTC, LauraMaier commented on AixLib/Fluid/HeatExchangers/Examples/HeatingRod.mo
>      Q_flow_nominal=100,
hmm, that is a bit ugly, dont you think?

2022-10-13 17:17 UTC, LauraMaier commented on AixLib/Fluid/MassExchangers/MembraneBasedEnthalpyExchangers/BaseClasses/Functions/CollisionIntegral.mo
> +  constant Real kB(unit="J/K") = 1.38064852E-23 "Stefan-Boltzmann-Constant";
You can use: Modelica.Constants.sigma ;-)

2022-10-13 17:19 UTC, LauraMaier commented on AixLib/Fluid/Movers/PumpsPolynomialBased/PumpHeadControlled.mo
> +    initType=Modelica.Blocks.Types.Init.InitialOutput, n = 1,y_start=Hstart)
delete spaces around n=1

2022-10-13 17:19 UTC, LauraMaier commented on AixLib/ThermalZones/ReducedOrder/Multizone/BaseClasses/MultizonePostProcessing.mo
> +      each displayUnit= "degC") "Air temperature of each zone"
delete space in front of degC?

2022-10-13 17:21 UTC, LauraMaier commented on AixLib/ThermalZones/ReducedOrder/SolarGain/CorrectionGDoublePane.mo
>    //Calculating the correction factor for direct solar radiation
unnecessary?

2022-10-13 17:23 UTC, LauraMaier commented on AixLib/ThermalZones/ReducedOrder/Windows/Validation/SelfShadowing/SelfShadowingTestBelow.mo
>      final dBel={0.01},
delete space?

2022-10-13 17:24 UTC, LauraMaier commented on AixLib/ThermalZones/ReducedOrder/Windows/Validation/SelfShadowing/SelfShadowingTestBelow.mo
> +    final til= {1.5707963267949},
same here

2022-10-13 17:24 UTC, LauraMaier commented on AixLib/ThermalZones/ReducedOrder/Windows/Validation/SelfShadowing/SelfShadowingTestLeft.mo
>      final dLef={0.01})
same here

2022-10-13 17:24 UTC, LauraMaier commented on AixLib/ThermalZones/ReducedOrder/Windows/Validation/SelfShadowing/SelfShadowingTestRight.mo
>      final bRig={1},
same here

2022-10-13 17:26 UTC, LauraMaier commented on AixLib/package.mo
>  					  ),
You forgot to update the version at the top to 1.3.2, right?

2022-10-13 17:27 UTC, LauraMaier requested changes
Great work everyone. Some minor changes to make nicer code + you forgot to update the AL version and you can use Stephan Boltzmann constant as already implemented in MSL :)

2022-10-14 06:36 UTC, FWuellhorst commented on AixLib/ThermalZones/ReducedOrder/SolarGain/CorrectionGDoublePane.mo
>    //Calculating the correction factor for direct solar radiation
and should not be possible, as it's an IBPSA file :D OpenModelica does not care about the lock in Dymola.

2022-10-14 06:38 UTC, FWuellhorst commented on AixLib/ThermalZones/ReducedOrder/SolarGain/CorrectionGDoublePane.mo
>    //Calculating the correction factor for direct solar radiation
Mhm, then we have to make a PR to IBPSA. I will handle that.

2022-10-14 06:43 UTC, FWuellhorst commented on AixLib/Fluid/MassExchangers/MembraneBasedEnthalpyExchangers/BaseClasses/Functions/CollisionIntegral.mo
> +  constant Real kB(unit="J/K") = 1.38064852E-23 "Stefan-Boltzmann-Constant";
Sigma equals  5.6703744191844314E-08.
You `Modelica.Constants.k`

2022-10-14 06:47 UTC, FWuellhorst commented on AixLib/Fluid/DistrictHeatingCooling/Pipes/StaticPipe.mo
>      annotation (Dialog(tab="Initialization"));
I like the equal sign in the first line more. A dangling one is not used in math.

2022-10-14 06:49 UTC, FWuellhorst commented on AixLib/Fluid/DistrictHeatingCooling/Pipes/PlugFlowPipeEmbedded.mo
>      annotation (Dialog(tab="Initialization"));
see other comment

2022-10-14 06:55 UTC, FWuellhorst commented on AixLib/ThermalZones/ReducedOrder/RC/OneElement.mo
> +  parameter Integer nOrientations(min=1)=1 "Number of orientations"
This one has to be solved in IBPSA. But im not sure we even need it.

2022-10-14 07:39 UTC, FWuellhorst commented on AixLib/ThermalZones/ReducedOrder/SolarGain/BaseClasses/PartialCorrectionG.mo
> +  parameter Integer n(min = 1)=1 "Vector size for input and output";
revert

2022-10-14 17:12 UTC, LauraMaier commented on AixLib/Fluid/MassExchangers/MembraneBasedEnthalpyExchangers/BaseClasses/Functions/CollisionIntegral.mo
> +  constant Real kB(unit="J/K") = 1.38064852E-23 "Stefan-Boltzmann-Constant";
oh sorry, I didnt check the units, just the name. But then use Modelica.Constants.k instead

2022-10-24 13:34 UTC, KremerMartin commented on AixLib/Fluid/MassExchangers/MembraneBasedEnthalpyExchangers/BaseClasses/Functions/CollisionIntegral.mo
> +  constant Real kB(unit="J/K") = 1.38064852E-23 "Stefan-Boltzmann-Constant";
That was my mistakes (nearly 2 years ago). But nice that this is finally found. You are right, it is not neccessary to define it once more.

2022-10-24 13:36 UTC, KremerMartin commented on AixLib/Fluid/MassExchangers/MembraneBasedEnthalpyExchangers/BaseClasses/Functions/CollisionIntegral.mo
> +  constant Real kB(unit="J/K") = Modelica.Constants.k "Stefan-Boltzmann-Constant";
@FWuellhorst Thanks for that correction you did on my model. But is it neccessary to define a constant that equals a already defined constant?
I would have directly used it in the calculation of `epsAir` and `epsSteam`.

2022-10-24 13:41 UTC, FWuellhorst commented on AixLib/Fluid/MassExchangers/MembraneBasedEnthalpyExchangers/BaseClasses/Functions/CollisionIntegral.mo
> +  constant Real kB(unit="J/K") = Modelica.Constants.k "Stefan-Boltzmann-Constant";
Yes, please go ahead

2022-11-11 15:49 UTC, FWuellhorst commented
@LauraMaier I added all requested changes. The CI now works :)

2022-11-18 08:32 UTC, FWuellhorst commented
@LauraMaier can you review again? :)

2022-11-22 22:36 UTC, LauraMaier commented on AixLib/Fluid/DistrictHeatingCooling/Pipes/DHCPipe.mo
Should we set it final?

2022-11-22 22:38 UTC, LauraMaier commented on AixLib/Fluid/DistrictHeatingCooling/Pipes/DHCPipe.mo
>      final m_flow_nominal=m_flow_nominal,
Just realized some paths are not full paths (AixLib.Fluid.MixingVolume...

2022-11-22 22:40 UTC, LauraMaier commented on AixLib/Fluid/DistrictHeatingCooling/Pipes/DHCPipe.mo
>    connect(pipCor.heatPort, cylHeaTra1.port_a)
unnecessary?

2022-11-22 22:43 UTC, LauraMaier commented on AixLib/Fluid/DistrictHeatingCooling/Pipes/PlugFlowPipeZeta.mo
> +  extends AixLib.Fluid.Interfaces.PartialTwoPortInterface(show_T=true);
Again maybe final?

2022-11-22 22:43 UTC, LauraMaier commented on AixLib/Fluid/DistrictHeatingCooling/Pipes/StaticPipe.mo
> +  extends AixLib.Fluid.Interfaces.PartialTwoPortInterface(show_T=true);
final?

2022-11-22 22:44 UTC, LauraMaier commented on AixLib/Fluid/HeatExchangers/Examples/HeatingRod.mo
> +
better get it from the medium model?

2022-11-22 22:48 UTC, LauraMaier commented on AixLib/Fluid/Humidifiers/GenericHumidifier_u.mo
>      annotation (Placement(transformation(extent={{-100,-50},{-80,-30}})));
Please check the whole model again and see if you can put some parameters final. Especially for the real expressions, etc.

2022-11-22 22:48 UTC, LauraMaier commented on AixLib/Fluid/Humidifiers/GenericHumidifier_u.mo
>    annotation (Icon(coordinateSystem(preserveAspectRatio=false, extent={{-100,
Please update revision section as these changes are more substantial :)

2022-11-22 22:50 UTC, LauraMaier commented on AixLib/Fluid/Movers/PumpsPolynomialBased/PumpHeadControlled.mo
>    // Initialization
No changes here

2022-11-22 22:50 UTC, LauraMaier commented on AixLib/Fluid/Movers/PumpsPolynomialBased/PumpHeadControlled.mo
> +// Dynamics
same here

2022-11-22 22:53 UTC, LauraMaier commented on AixLib/Fluid/Movers/PumpsPolynomialBased/PumpHeadControlled.mo
> +                                                      color={0,0,127}), Text(
please delete ugly white space :)

2022-11-22 22:53 UTC, LauraMaier commented on AixLib/Fluid/Movers/PumpsPolynomialBased/PumpHeadControlled.mo
>        string="%second",
same here: ugly white space :)

2022-11-22 22:53 UTC, LauraMaier commented on AixLib/Fluid/Movers/PumpsPolynomialBased/PumpHeadControlled.mo
>        string="%second",
again

2022-11-22 22:54 UTC, LauraMaier commented on AixLib/Resources/ReferenceResults/Dymola/AixLib_Fluid_Movers_PumpsPolynomialBased_Examples_PumpSpeedControlled.txt
> +last-generated=2022-10-14
I think there is something wrong as the ref results did not change, just the date?

2022-11-22 22:55 UTC, LauraMaier commented on AixLib/Resources/ReferenceResults/Dymola/AixLib_Fluid_Movers_PumpsPolynomialBased_Examples_PumpSpeedControlledDpV.txt
> +last-generated=2022-10-14
same here :) Maybe we revert it

2022-11-22 22:56 UTC, LauraMaier commented on AixLib/Systems/HydraulicModules/Example/Admix.mo
>      Icon(graphics,
A revision update would be nice

2022-11-22 22:56 UTC, LauraMaier commented on AixLib/Systems/HydraulicModules/Example/Injection.mo
>          rotation=90,
same here: revision update maybe? :)

2022-11-22 22:56 UTC, LauraMaier commented on AixLib/Systems/HydraulicModules/Example/Injection2WayValve.mo
>          extent={{-24,-24},{24,24}},
and same here: revision update maybe?

2022-11-22 22:57 UTC, LauraMaier commented on AixLib/Systems/HydraulicModules/Example/Pump.mo
>      Transfer from ZUGABE to AixLib.
Update revision? :)

2022-11-22 22:58 UTC, LauraMaier commented on AixLib/Systems/HydraulicModules/Example/Pump.mo
>                Icon(graphics,
some of these changes appear as if they were new but they did not change. Can you adapt it so that the actual changes become more apparent?

2022-11-22 22:58 UTC, LauraMaier commented on AixLib/Systems/HydraulicModules/Example/ThrottlePump.mo
>              -100},{120,100}})),                                  Diagram(
Update revisions?

2022-11-22 22:59 UTC, LauraMaier commented on AixLib/Systems/ModularAHU/Examples/Cooler.mo
>    Fluid.Sources.Boundary_pT boundaryWaterSource(
Here, the git history is also a bit screwed up. e.g.: lines 22 and 23 are the same as lines 31 and 32

2022-11-22 23:00 UTC, LauraMaier commented on AixLib/Systems/ModularAHU/Examples/Heater.mo
>        Q_nom=30000,
? do we need this blank line?

2022-11-22 23:01 UTC, LauraMaier commented on AixLib/Systems/ModularAHU/Examples/Heater.mo
>      annotation (Placement(transformation(extent={{-40,-46},{26,40}})));
again strange git history

2022-11-22 23:05 UTC, LauraMaier commented on AixLib/Systems/ModularAHU/Validation/AHU2_Cooler.mo
>    This example compares the simulated behavior with measured data. The
Consider updating the revision section

2022-11-22 23:06 UTC, LauraMaier commented on AixLib/ThermalZones/ReducedOrder/Multizone/BaseClasses/MultizonePostProcessing.mo
> -﻿within AixLib.ThermalZones.ReducedOrder.Multizone.BaseClasses;
I see no change here?

2022-11-22 23:07 UTC, LauraMaier commented on AixLib/ThermalZones/ReducedOrder/SolarGain/CorrectionGDoublePane.mo
> +end CorrectionGDoublePane;
?

2022-11-22 23:10 UTC, LauraMaier commented on AixLib/ThermalZones/ReducedOrder/Windows/Validation/SelfShadowing/SelfShadowingTestAbove.mo
>      "Shadowing due to a projection above the window"
please check again: if you open the model, the tilt of incAng1 is 5156 and the display unit is degree. I think it got mixed up with the rad unit here transfering 90 rad to degree insteadt of 90 degree

2022-11-22 23:11 UTC, LauraMaier commented on AixLib/ThermalZones/ReducedOrder/Windows/Validation/SelfShadowing/SelfShadowingTestBelow.mo
>      final bBel={1}) "Shadowing due to a projection below"
Same problem here: Change to rad

2022-11-22 23:11 UTC, LauraMaier commented on AixLib/ThermalZones/ReducedOrder/Windows/Validation/SelfShadowing/SelfShadowingTestLeft.mo
>      final dLef={0.01})
same here

2022-11-22 23:13 UTC, LauraMaier requested changes

2022-11-22 23:13 UTC, LauraMaier commented on AixLib/ThermalZones/ReducedOrder/Windows/Validation/SelfShadowing/SelfShadowingTestRight.mo
> +    final azi={0},
and one more :)

2022-11-22 23:13 UTC, LauraMaier commented on AixLib/ThermalZones/ReducedOrder/Windows/Validation/VDI2078/TestCase1_Illumination.mo
> +    til={1.5707963267949})
![image](https://user-images.githubusercontent.com/38097212/203439862-5b50e22b-9296-47dc-882a-315d25bf8fae.png)

2022-12-01 08:26 UTC, FWuellhorst commented on AixLib/Fluid/DistrictHeatingCooling/Pipes/DHCPipe.mo
I don't see the point, if you want to speed up the simulation, final would disable that.

2022-12-01 08:26 UTC, FWuellhorst commented on AixLib/Fluid/DistrictHeatingCooling/Pipes/DHCPipe.mo
>      final m_flow_nominal=m_flow_nominal,
True. The question is: Do we want to only fix the OpenModelica issues, or fix the models as well?

2022-12-01 08:27 UTC, FWuellhorst commented on AixLib/Fluid/DistrictHeatingCooling/Pipes/PlugFlowPipeZeta.mo
> +  extends AixLib.Fluid.Interfaces.PartialTwoPortInterface(show_T=true);
see above

2022-12-01 08:27 UTC, FWuellhorst commented on AixLib/Fluid/DistrictHeatingCooling/Pipes/StaticPipe.mo
> +  extends AixLib.Fluid.Interfaces.PartialTwoPortInterface(show_T=true);
see above

2022-12-01 08:27 UTC, FWuellhorst commented on AixLib/Fluid/HeatExchangers/Examples/HeatingRod.mo
> +
For a model, yes. But it's just an example. I don't see the benefit of adding the state etc.

2022-12-01 08:28 UTC, FWuellhorst commented on AixLib/Fluid/Humidifiers/GenericHumidifier_u.mo
>      annotation (Placement(transformation(extent={{-100,-50},{-80,-30}})));
See above: Settings parameters to final in the PR would change model behavior.

2022-12-06 11:47 UTC, FWuellhorst commented on AixLib/ThermalZones/ReducedOrder/Windows/Validation/BaseClasses/IncidenceAngleVDI6007.mo
> +  parameter Modelica.Units.SI.Angle til(displayUnit="deg")
This change results in the "wrong" parameters. However, I think we found a larger issue of the ROM. It was always a wrong value in `AixLib.ThermalZones.ReducedOrder.Windows.Validation.BaseClasses.IncidenceAngleVDI6007`.

2022-12-06 11:47 UTC, FWuellhorst commented on AixLib/ThermalZones/ReducedOrder/Windows/Validation/SelfShadowing/SelfShadowingTestAbove.mo
>      "Shadowing due to a projection above the window"
See my other comment.

2022-12-06 11:47 UTC, FWuellhorst commented on AixLib/ThermalZones/ReducedOrder/Windows/Validation/SelfShadowing/SelfShadowingTestLeft.mo
>      final dLef={0.01})
This is not an error! Removing displayUnit does not change anything. The screenshot of yours is a different submodel.

2022-12-06 11:47 UTC, FWuellhorst commented on AixLib/ThermalZones/ReducedOrder/Windows/Validation/VDI2078/TestCase1_Illumination.mo
> +    til={1.5707963267949})
See my other comment.

2022-12-06 11:50 UTC, FWuellhorst commented on AixLib/ThermalZones/ReducedOrder/Windows/Validation/BaseClasses/IncidenceAngleVDI6007.mo
> +  parameter Modelica.Units.SI.Angle til(displayUnit="deg")
Ok, the model is outdated and was moved to `AixLib.BoundaryConditions.SolarGeometry.IncidenceAngle`. No ROM model is affected, only the validation cases.

2022-12-06 11:55 UTC, FWuellhorst commented on AixLib/ThermalZones/ReducedOrder/Multizone/BaseClasses/MultizonePostProcessing.mo
> -﻿within AixLib.ThermalZones.ReducedOrder.Multizone.BaseClasses;
This is weird linebreak stuff, if the pipeline passes, linebreaks are fine

2022-12-06 12:03 UTC, FWuellhorst commented on AixLib/ThermalZones/ReducedOrder/SolarGain/CorrectionGDoublePane.mo
> +end CorrectionGDoublePane;
I manually copied the file from the current dev. Silly linebreaks ... Dont know how to fix this..

2022-12-06 12:06 UTC, FWuellhorst commented on AixLib/Systems/ModularAHU/Examples/Heater.mo
>      annotation (Placement(transformation(extent={{-40,-46},{26,40}})));
Yes, but Dymola 2023 saves it like this. Reverting this would lead to a change in the next commit of this model.

2022-12-06 13:26 UTC, FWuellhorst commented
@LauraMaier : I added all changes or commented my concerns. Please re-review :)

2023-01-30 13:36 UTC, LauraMaier requested changes

2023-01-30 13:36 UTC, LauraMaier commented on AixLib/Fluid/Humidifiers/GenericHumidifier_u.mo
>    Modelica.Blocks.Interfaces.RealInput Tsteam_intern;
changes not necessary and not nicer from a code-structure perspective? Revert?

2023-01-30 13:36 UTC, LauraMaier commented on AixLib/Fluid/Humidifiers/GenericHumidifier_u.mo
>    connect(Tsteam.y, Tsteam_intern);
Revert?

2023-01-30 13:36 UTC, LauraMaier commented on AixLib/Resources/ReferenceResults/Dymola/AixLib_Fluid_Movers_PumpsPolynomialBased_Examples_PumpSpeedControlled.txt
>  statistics-initialization=
Since the actual data has not changed, maybe revert?

2023-01-30 13:36 UTC, LauraMaier commented on AixLib/Systems/HydraulicModules/Example/Pump.mo
>      Placement(visible = true, transformation(origin = {-86, -28}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
Again: not nicer and not necessary?

2023-01-30 13:36 UTC, LauraMaier commented on AixLib/Systems/HydraulicModules/Injection.mo
>    <li>August 09, 2018, by Alexander Kümpel:<br/>
And your name is missing :)

2023-01-30 13:36 UTC, LauraMaier commented on AixLib/Systems/HydraulicModules/Injection.mo
>    <li>August 09, 2018, by Alexander Kümpel:<br/>
or add FG Modelica as below. Maybe we can discuss if that is the general approach for group effort.

2023-01-30 13:37 UTC, LauraMaier commented
Thanks for the nice work, only minor changes from my side. And please make sure the changes in the bin directory are intended :)

2023-02-08 13:27 UTC, FWuellhorst commented on AixLib/Fluid/Humidifiers/GenericHumidifier_u.mo
>    connect(Tsteam.y, Tsteam_intern);
No, it's an empty line instead of a line with whitespaces @LauraMaier .

2023-02-08 14:05 UTC, FWuellhorst commented
@LauraMaier : I resolved all open issues. Please check again :)

2023-02-09 07:40 UTC, LauraMaier approved these changes
Thanks for the nice, extensive work! :)

2023-02-09 07:41 UTC, merged