Issue1320 add example for ahu control
RWTH-EBC/AixLib pull request #1380
Opened 2022-10-18 07:27 UTC by KremerMartin

Closes #1320 

With his pull-request we will add a new example for `AixLib.Systems.ModularAHU.GenericAHU`. The example combines the air handling unit model with a thermal zone and a DCV-strategy.

A new controller is added containing the CO2-based DCV and the already existing AHU-control.
Some database for the thermal zone and a record for internal gains in single offices according to SIA 2024 is also added.

2022-10-19 17:16 UTC, LauraMaier requested changes

2022-10-19 17:16 UTC, LauraMaier commented on AixLib/Systems/ModularAHU/Controller/CtrAHUCO2.mo
> +<p>This control uses the heating and cooling register to regulate the supply air temperature. The set point of the supply air can be given either by the parameter <i>TFlowSet </i>or by the external i
Typo here: "The preheater use used..."

2022-10-19 17:16 UTC, LauraMaier commented on AixLib/Systems/ModularAHU/Controller/CtrAHUCO2.mo
> +    final initType=initType,
why not final Td?

2022-10-19 17:16 UTC, LauraMaier commented on AixLib/Systems/ModularAHU/Controller/CtrAHUCO2.mo
> +    final initType=initType) if usePreheater annotation (dialog(group="Register controller",
Why not final Td?

2022-10-19 17:16 UTC, LauraMaier commented on AixLib/Systems/ModularAHU/Controller/CtrAHUCO2.mo
> +    final reverseActing=true,
Why not final y_start?

2022-10-19 17:16 UTC, LauraMaier commented on AixLib/Systems/ModularAHU/Controller/CtrAHUCO2.mo
> +    final reverseActing=true,
same here

2022-10-19 17:16 UTC, LauraMaier commented on AixLib/Systems/ModularAHU/Controller/CtrAHUCO2.mo
> +    final reverseActing=false,
and here

2022-10-19 17:16 UTC, LauraMaier commented on AixLib/Systems/ModularAHU/Controller/CtrAHUCO2.mo
> +    final reverseActing=true,
and here

2022-10-19 17:16 UTC, LauraMaier commented on AixLib/Systems/ModularAHU/Controller/CtrAHUCO2.mo
> +  connect(constCO2Set.y, PID_CO2.u_s) annotation (Line(points={{-79,-28},{-74,-28},{-74,-50},{-70,-50}}, color={0,0,127}));
obsolete? :)

2022-10-19 17:16 UTC, LauraMaier commented on AixLib/Systems/ModularAHU/Examples/package.order
> +AhuDcv
hm the name is not really self explaining to me. What do you think?

2022-10-19 17:16 UTC, LauraMaier commented on AixLib/Systems/ModularAHU/Examples/AhuDcv.mo
> +model AhuDcv "Example for air hanling unit with demand controlled ventilation"
Please add a documentation for the nice example! :) Some explaining phrases will be enough

2022-10-19 17:16 UTC, LauraMaier commented on AixLib/Systems/ModularAHU/Examples/AhuDcv.mo
> +    zoneParam=AixLib.DataBase.ThermalZones.Office_1995_1000(),
You use a lot of fixed absolute values here. Like C_Start. Maybe you can define the basic parameters which form these numbers so that externals can better understand what th eintention is?

2022-10-19 17:16 UTC, LauraMaier commented on AixLib/Systems/ModularAHU/Examples/AhuDcv.mo
> +    TFlowSet=293.15,
maybe rename without the _1

2022-10-19 17:16 UTC, LauraMaier commented on AixLib/Systems/ModularAHU/Examples/AhuDcv.mo
> +model AhuDcv "Example for air hanling unit with demand controlled ventilation"
Please link the simulate and plot script to that model. You dont have it in the experiment annotation yet :)

2022-10-19 17:16 UTC, LauraMaier commented on AixLib/Systems/ModularAHU/Examples/AhuDcv.mo
> +        Q_nom=57700)),
Some numbers seem a bit random to me. Maybe you could introduce them on the top level and add a description? e.g. why 43.9 :D

2022-10-20 06:42 UTC, KremerMartin commented on AixLib/Resources/LowOrder_ExampleData/SIA2024_SingleOffice_week.txt
> +57600	0.8	0.8	1
To get a step-signal with a smoother change in the Input (no abrupt event at Time X, which is also not possible in TimeTables. :D) If one omits the 10 sec-Steps it will lead to a interpolated increase in Occupancy. This is more like nearly steady-state occupancy.

2022-10-20 06:43 UTC, KremerMartin commented on AixLib/Resources/LowOrder_ExampleData/SIA2024_SingleOffice_week.txt
> +3600	0	0.1	0
Good question. I don't know... XD

2022-10-20 11:36 UTC, KremerMartin commented on AixLib/Systems/ModularAHU/Controller/CtrAHUCO2.mo
> +    final initType=initType,
Since the user should be able to use the Controller as _PID-Controller_ if wanted. In this way it will be per default a _PI-Controller_, but can be changed, if wanted.

2022-10-20 11:37 UTC, KremerMartin commented on AixLib/Systems/ModularAHU/Controller/CtrAHUCO2.mo
> +    final initType=initType) if usePreheater annotation (dialog(group="Register controller",
Since the user should be able to use the Controller as _PID-Controller_ if wanted. In this way it will be per default a _PI-Controller_, but can be changed, if wanted.

2022-10-20 12:00 UTC, KremerMartin commented on AixLib/Systems/ModularAHU/Examples/AhuDcv.mo
> +    zoneParam=AixLib.DataBase.ThermalZones.Office_1995_1000(),
I see what you mean. In this very case, C_start gets the value of 400 ppm, since the C_flow represents the CO2-concentration in the thermal zone. The value is given in a mass fraction. Since ppm is a unit for volume fraction it has to be recalculated using the molar masses of CO2 and air. I thought it was not that important to show that calculation, but I can add it.

2022-10-21 09:39 UTC, KremerMartin commented on AixLib/Systems/ModularAHU/Controller/CtrAHUCO2.mo
> +    final reverseActing=true,
Now the y_start is set to zero per default for all PI(D)-controller. But for some use-cases it will be reasonable to redefine the y_start in different ways for the different controllers.
e.g. the PID for CO2 has a volume flow rate as output and the PID for heater/cooler have the valve position between 0 and 1 as output. If the start value shall not be zero, the initial outputs for the PIDs should obviously be different.
To avoid introducing `y_start` for each PID seperately, only one value is defined. If different start values shall be used, it can be done by changing the `y_start` in the control blocks directly. Therefore `y_start` is not defined final.

2022-10-21 09:39 UTC, KremerMartin commented on AixLib/Systems/ModularAHU/Controller/CtrAHUCO2.mo
> +    final reverseActing=true,
see above

2022-10-21 09:39 UTC, KremerMartin commented on AixLib/Systems/ModularAHU/Controller/CtrAHUCO2.mo
> +    final reverseActing=false,
see above

2022-10-21 09:39 UTC, KremerMartin commented on AixLib/Systems/ModularAHU/Controller/CtrAHUCO2.mo
> +    final reverseActing=true,
see above

2022-10-21 16:53 UTC, LauraMaier commented on AixLib/Systems/ModularAHU/Examples/DemandControlledAHU.mo
> +model DemandControlledAHU "Example for air hanling unit with demand controlled ventilation"
small typo :) handling

2022-10-21 16:56 UTC, LauraMaier approved these changes
Please undo the unnecessary commits with the connect statement annotations and fix typo. Then you are good to go.
Great work, thanks @martinkremer :)

2022-10-21 16:56 UTC, LauraMaier commented on AixLib/Systems/ModularAHU/Examples/GenericAHU.mo
>    connect(SourceCooler.ports[1], genericAHU.port_a4) annotation (Line(points={{
unnecessary commit

2022-10-21 16:56 UTC, LauraMaier commented on AixLib/Systems/ModularAHU/Examples/GenericAHU.mo
> +                                                      color={0,127,255}));
here as well

2022-10-21 16:56 UTC, LauraMaier commented on AixLib/Systems/ModularAHU/Examples/EONERC_AHU2.mo
>    connect(ctrAHUBasic.genericAHUBus, genericAHU.genericAHUBus) annotation (Line(
unnecessary commits

2022-10-24 14:05 UTC, LauraMaier approved these changes

2022-10-24 15:02 UTC, merged