1367 geothermalheatpump example fails in openmodelica
RWTH-EBC/AixLib pull request #1441
Opened 2023-06-06 10:38 UTC by HannahRomberg

Closes #1367 

The flow direction from the cold storage to the evaporator was going in the wrong direction. The heating coil orientation was changed to down->up and the port connections were changed to allow the flow in the right direction.

2023-06-06 10:58 UTC, FWuellhorst requested changes
Please change the name and check if the new connection is required. If the line is better now, you can leave it.

2023-06-06 10:58 UTC, FWuellhorst commented on AixLib/Fluid/Examples/GeothermalHeatPump/BaseClasses/GeothermalHeatPumpBase.mo
> -  connect(heatPump.port_b2, coldStorage.portHC1Out) annotation (Line(points={{
These connections seem to be the same as before?!

2023-06-06 10:58 UTC, FWuellhorst commented on AixLib/Fluid/Examples/GeothermalHeatPump/BaseClasses/GeothermalHeatPumpBase.mo
> +    PeakLoadDeviceModel PeakLoadDevice
Minor: 
A model has capital names `PeakLoadDeviceModel`. The instance of a model should be lower case, e.g. `peaLoaDev` (three letter camel-case name according to guidelines)

2023-07-12 11:42 UTC, DaJansenGit commented
The previous pipelines failed due to another, not already solved, problem with the `AixLib.Controls.HVACAgentBasedControl` package. For now, I put the models on the whitelist and opened issue #1447 which needs to be solved independent from this pull request.

2023-07-17 08:41 UTC, HannahRomberg reviewed
Adressed requested changes. See comments.

2023-07-17 08:48 UTC, FWuellhorst approved these changes
Looks good, thanks!

2023-07-17 08:49 UTC, merged