Issue1451 add pvt model
RWTH-EBC/AixLib pull request #1458
Opened 2023-08-24 15:37 UTC by Philipp-Schmitz

added a simple photovoltaic thermal collector based on the already existing solar thermal model

2023-09-19 05:27 UTC, FWuellhorst requested changes
Thanks for this addition to the AixLib.

The equation look correct, but there are some style-guide issues which need to be addressed. If you have questions, just comment below. Most of them were already wrong in the SolarThermal model, but we agreed on fixing those issues if we adapt existing models.

2023-09-19 05:27 UTC, FWuellhorst commented on AixLib/DataBase/PhotovoltaicThermal/ElectricalGlazedPVTWithLowEmissionCoating.mo
> +<p><b><span style=\"color: #008000;\">References</span> </b></p>
Replace `<b><span style=\"color: #008000;\">Overview</span>` with `<h4>Overview</h4>` . This is a bug in Dymola, sadly. Same for References.

2023-09-19 05:27 UTC, FWuellhorst commented on AixLib/DataBase/PhotovoltaicThermal/ElectricalGlazedPVTWithLowEmissionCoating.mo
> +<li>implemented </li>
Please update the Date and put your and my name in it.

2023-09-19 05:27 UTC, FWuellhorst commented on AixLib/DataBase/PhotovoltaicThermal/ElectricalGlazedPVTWithLowEmissionCoating.mo
> +<p>Record is used in model <a href=\"AixLib.Fluid.Solar.Thermal.SolarThermal\">AixLib.Fluid.Solar.Thermal.SolarThermal</a>. </p>
It should be `a href=\"modelica://AixLib`. This way, the link will actually work

2023-09-19 05:27 UTC, FWuellhorst commented on AixLib/DataBase/PhotovoltaicThermal/ElectricalGlazedPVTWithoutLowEmissionCoating.mo
> +</ul>
Please apply the same comments to all the other records.

2023-09-19 05:27 UTC, FWuellhorst commented on AixLib/DataBase/PhotovoltaicThermal/PhotovoltaicThermalBaseDataDefinitionElectrical.mo
> +  parameter Real m(unit = "W/(m.m.K)") "gradient of linear approximation";
Is this unit correct?

2023-09-19 05:27 UTC, FWuellhorst commented on AixLib/DataBase/PhotovoltaicThermal/PhotovoltaicThermalBaseDataDefinitionElectrical.mo
> +  Base data definition for record to be used in model <a href=
Apply the same doc comments as above: Our names, span -> h4, and modelica://

2023-09-19 05:27 UTC, FWuellhorst commented on AixLib/DataBase/PhotovoltaicThermal/SolarThermalBaseDataDefinition.mo
> +  </li>
Why is this file added now?

2023-09-19 05:27 UTC, FWuellhorst commented on AixLib/DataBase/PhotovoltaicThermal/package.mo
> +
Remove redundant white lines

2023-09-19 05:27 UTC, FWuellhorst commented on AixLib/DataBase/PhotovoltaicThermal/package.order
> +SolarThermalBaseDataDefinition
Just minor: Please adjust order alphabetical.

2023-09-19 05:27 UTC, FWuellhorst commented on AixLib/DataBase/PhotovoltaicThermal/SolarThermalBaseDataDefinition.mo
> +  </li>
Ah ok, it was copied from SolarThermal. Does it differ in any way from the other record? If not, we don't need this here.

2023-09-19 05:27 UTC, FWuellhorst commented on AixLib/Fluid/Solar/Thermal/BaseClasses/PVT_SolarThermalEfficiency.mo
> +  </li>
Only one revision, our names. Same for the other models.

2023-09-19 05:27 UTC, FWuellhorst commented on AixLib/Fluid/Solar/Thermal/BaseClasses/PVT_SolarThermalEfficiency.mo
> +    Collector=AixLib.DataBase.PhotovoltaicThermal.PVT_thermal()
Is this the same model as the existing model? If so, do we really need it?

2023-09-19 05:27 UTC, FWuellhorst commented on AixLib/Fluid/Solar/Thermal/BaseClasses/SolarElectricalEfficiency.mo
> +<p><b><span style=\"color: #008000;\">Overview</span> </b></p>
see above

2023-09-19 05:27 UTC, FWuellhorst commented on AixLib/Fluid/Solar/Thermal/BaseClasses/SolarElectricalEfficiency.mo
> +  Modelica.Blocks.Interfaces.RealInput T_air(
Rename to `TAir`. Same for the other models. I know this is currently not the case in AixLib, but we want to follow the naming guidelines more thoroughly.

2023-09-19 05:27 UTC, FWuellhorst commented on AixLib/Fluid/Solar/Thermal/BaseClasses/SolarElectricalEfficiency.mo
> +  Modelica.Blocks.Interfaces.RealInput T_col(
TCol

2023-09-19 05:27 UTC, FWuellhorst commented on AixLib/Fluid/Solar/Thermal/BaseClasses/SolarElectricalEfficiency.mo
> +  Modelica.Blocks.Interfaces.RealOutput P_el(quantity="ElectricPower", unit="W/m2")
PEle

2023-09-19 05:27 UTC, FWuellhorst commented on AixLib/Fluid/Solar/Thermal/BaseClasses/SolarElectricalEfficiency.mo
> +    Collector=AixLib.DataBase.PhotovoltaicThermal.ElectricalGlazedPVTWithLowEmissionCoating()
Collector --> `parCol` for parameters of collector

2023-09-19 05:27 UTC, FWuellhorst commented on AixLib/Fluid/Solar/Thermal/Examples/PhotovoltaicThermalCollector.mo
> +  AixLib.Fluid.Solar.Thermal.PhotovoltaicThermal pVT_Modul(
phoVolThe? Or pvt?

2023-09-19 05:27 UTC, FWuellhorst commented on AixLib/Fluid/Solar/Thermal/PhotovoltaicThermal.mo
> +    Collector = AixLib.DataBase.SolarThermal.SimpleAbsorber()
parCol

2023-09-19 05:27 UTC, FWuellhorst commented on AixLib/Fluid/Solar/Thermal/PhotovoltaicThermal.mo
> +  Modelica.Blocks.Interfaces.RealInput T_air(
TAir

2023-09-19 05:27 UTC, FWuellhorst commented on AixLib/Fluid/Solar/Thermal/PhotovoltaicThermal.mo
> +  Modelica.Blocks.Interfaces.RealInput Irradiation(
irr

2023-09-19 05:27 UTC, FWuellhorst commented on AixLib/Fluid/Solar/Thermal/PhotovoltaicThermal.mo
> +  Modelica.Blocks.Math.Gain convertRelHeatFlow2absHeatFlow(final k=A)
conRelHeaFlowToAbsHeaFlow

2023-09-19 05:27 UTC, FWuellhorst commented on AixLib/Fluid/Solar/Thermal/PhotovoltaicThermal.mo
> +  Modelica.Blocks.Math.Add calcTempMean(k1=0.5, k2=0.5) annotation (Placement(
calcMeaT

2023-09-19 05:27 UTC, FWuellhorst commented on AixLib/Fluid/Solar/Thermal/PhotovoltaicThermal.mo
> +        Modelica.Blocks.Interfaces.RealOutput DCOutputPower(
PEle? Or is the DC part important?

2023-09-19 05:27 UTC, FWuellhorst commented on AixLib/Fluid/Solar/Thermal/PhotovoltaicThermal.mo
> +  BaseClasses.SolarElectricalEfficiency solarElectricalEfficiency
eleEff?

2023-09-19 05:27 UTC, FWuellhorst commented on AixLib/Fluid/Solar/Thermal/PhotovoltaicThermal.mo
> +  Modelica.Blocks.Math.Gain convertRelHeatFlow2absHeatFlow1(final k=A)
see above, but give clear name instead of `1`

2023-09-19 05:27 UTC, FWuellhorst commented on AixLib/Fluid/Solar/Thermal/PhotovoltaicThermal.mo
> +  BaseClasses.PVT_SolarThermalEfficiency pVT_SolarThermalEfficiency
pvtEff

2023-09-19 05:27 UTC, FWuellhorst commented on AixLib/Fluid/Solar/Thermal/PhotovoltaicThermal.mo
> +<td><p>0.079 </p><p><br>Assuming a default size for a unit of 2 m2 we get pressure losses for a module as in the following table (vfr=0.79 gpm): </p><p>&quot;Pressure drop of two flat collector modul
Did you write this section? If not, you can just refer to the SolarThermal model.

2023-09-19 05:27 UTC, FWuellhorst commented on AixLib/Fluid/Solar/Thermal/PhotovoltaicThermal.mo
> +<p><b><span style=\"color: #008000;\">Overview</span></b> </p>
Apply the same doc comments as above

2023-11-16 18:11 UTC, Philipp-Schmitz commented on AixLib/Fluid/Solar/Thermal/BaseClasses/PVT_SolarThermalEfficiency.mo
> +    Collector=AixLib.DataBase.PhotovoltaicThermal.PVT_thermal()
I created the extra model, because i did not want to mix the new thermal properties of the pvt model with the existing solar thermal paramters. This way when working with the pvt model, only the right kind of parameters are possible to select.

2023-11-16 18:32 UTC, Philipp-Schmitz commented on AixLib/DataBase/PhotovoltaicThermal/PhotovoltaicThermalBaseDataDefinitionElectrical.mo
> +  parameter Real m(unit = "W/(m.m.K)") "gradient of linear approximation";
yes, in the equation for the electrical efficiency, parameter m is in the same position as c1 is for the thermal efficiency. Therefore it has the same unit as c1.

2024-12-23 14:37 UTC, TobiasSpratte reviewed
Looks nice, thank you for the pvt model!

2024-12-23 14:37 UTC, TobiasSpratte commented on AixLib/Fluid/SolarCollectors/PhotovoltaicThermal/EN12975Curves.mo
> +    "Performance data for PV-Thermal"
maybe change the description in the EN12975 model from "performance data" to something like "performance data for Solar Thermal Collector". This could be helpful to understand that _per_ is only for the thermal part and _perPVT_ is both, thermal and electric.

2024-12-23 14:37 UTC, TobiasSpratte commented on AixLib/Fluid/SolarCollectors/PhotovoltaicThermal/EN12975Curves.mo
> +  this thesis </a> by Markus Lämmle, p.43
```suggestion
  this thesis</a> by Markus Lämmle, p.43
```

2024-12-23 14:37 UTC, TobiasSpratte commented on AixLib/Fluid/SolarCollectors/PhotovoltaicThermal/EN12975Curves.mo
> +    "Sum of all electrical gains"
```suggestion
    "Sum of all electrical gains and losses"
```

2024-12-23 14:37 UTC, TobiasSpratte commented on AixLib/Fluid/SolarCollectors/PhotovoltaicThermal/EN12975Curves.mo
> +  <li>ambient temperature Ta= 25°C
```suggestion
  <li>ambient temperature Ta=25 °C
```

2024-12-23 14:37 UTC, TobiasSpratte commented on AixLib/Fluid/SolarCollectors/PhotovoltaicThermal/EN12975Curves.mo
> +  <li>windspeed Uwind=3m/s
```suggestion
  <li>windspeed Uwind=3 m/s
```

2024-12-23 14:37 UTC, TobiasSpratte commented on AixLib/Fluid/SolarCollectors/PhotovoltaicThermal/Examples/BaseClasses/PartialExample.mo
> +  "Example to demonstrate the function of the photovoltaic thermal collector model"
"Partial example to demonstrate ... "?

2024-12-23 14:37 UTC, TobiasSpratte commented on AixLib/Fluid/SolarCollectors/PhotovoltaicThermal/Examples/BaseClasses/PartialExample.mo
> +        "Resources/Scripts/Dymola/Fluid/Solar/Thermal/Examples/SolarThermalCollector.mos"));
Is this script needed here?

2024-12-30 08:26 UTC, FWuellhorst commented on AixLib/Fluid/SolarCollectors/PhotovoltaicThermal/Examples/BaseClasses/PartialExample.mo
> +        "Resources/Scripts/Dymola/Fluid/Solar/Thermal/Examples/SolarThermalCollector.mos"));
No, good catch!

2024-12-30 08:28 UTC, FWuellhorst commented on AixLib/Fluid/SolarCollectors/PhotovoltaicThermal/EN12975Curves.mo
> +    "Performance data for PV-Thermal"
I used `"Performance data for both solar thermal collector and PV"`, is this better?

2025-01-21 07:51 UTC, FWuellhorst submitted a review, later dismissed

2025-01-21 11:12 UTC, FWuellhorst approved these changes

2025-01-21 11:13 UTC, merged