Issue1433 shadow model
RWTH-EBC/AixLib pull request #1464
Opened 2023-09-10 14:12 UTC by Jun-Jiang-92

In this issue, a new feature named "shadow model" is created. This model is built in the new package "AixLib.ThermalZones.HighOrder.Components.Shadow" and is integrated into the "AixLib.ThermalZones.HighOrder.Components.Walls.Wall" model.

By using shadow model, the impact of the shadow, generated by the horizontal shield above the window, will be considered. The solar heat gain through the window glazing will be reduced according to the shield length and shadow length during the simulaiton.

To activate the shadow model, it is necessary to activate the "withSunblind" in the tab "Window". And then, it is possible to activate "withShield" and input the parameters for the model.

2023-09-19 06:21 UTC, FWuellhorst requested changes
@Jun-Jiang-92 Thanks for this feature. I added minor styleguide requests. We have to discuss in person on why the weaBus is necessary and, if it is, how to best implement it.

2023-09-19 06:21 UTC, FWuellhorst commented on AixLib/ThermalZones/HighOrder/Components/Walls/Wall.mo
> +        iconTransformation(extent={{-29,-90},{-9,-70}})));
This will be quite hard to include in all HOM models, as you have to propagate the weaBus to all upper levels. Using the weaBus in general is a discussion on it's own. I have an adaptor for the BESMod.

2023-09-19 06:21 UTC, FWuellhorst commented on AixLib/ThermalZones/HighOrder/Components/Walls/Wall.mo
>    replaceable model WindowModel =
I know it was bad before, but can you remove redundant whitespaces and break lines so that it's fits a smaller screen? e.g. 80-100 linewidth

2023-11-17 12:00 UTC, Jun-Jiang-92 commented on AixLib/ThermalZones/HighOrder/Components/Shadow/Icon/Heliodon_SAcalcs.png
✅

2023-11-17 12:05 UTC, Jun-Jiang-92 commented on AixLib/ThermalZones/HighOrder/Components/Shadow/RadTrans.mo
> +model RadTrans "Radiation transformer for WeaBus"
Renamed to "RadiationTransfer"

2023-11-17 12:08 UTC, Jun-Jiang-92 commented on AixLib/ThermalZones/HighOrder/Components/Shadow/RadTrans.mo
> +  parameter Modelica.Units.NonSI.Angle_deg azi_deg = -54 "Surface azimuth, S=0°, W=90°, N=180°, E=-90°";
✅

2023-11-17 12:14 UTC, Jun-Jiang-92 commented on AixLib/ThermalZones/HighOrder/Components/Shadow/RadTrans.mo
> +  Utilities.Interfaces.SolarRad_out solarRad_out
✅

2023-11-17 12:22 UTC, Jun-Jiang-92 commented on AixLib/ThermalZones/HighOrder/Components/Shadow/ShadowLength.mo
> +    "If the shadow available"
✅

2023-11-17 12:33 UTC, Jun-Jiang-92 commented on AixLib/ThermalZones/HighOrder/Components/Shadow/ShadowLength.mo
> +  if tan(zen.zen)<1e-5 or cos(wallSolAzi.verAzi)<1e-5 then
✅

2023-11-17 14:20 UTC, Jun-Jiang-92 commented on AixLib/ThermalZones/HighOrder/Components/Shadow/RadTrans.mo
> +  Utilities.Sources.PrescribedSolarRad prescribedSolarRad
✅

2023-11-17 14:21 UTC, Jun-Jiang-92 commented on AixLib/ThermalZones/HighOrder/Components/Shadow/ShadowEff.mo
> +  ShadowLength shadowLength(azi_deg=azi_deg, L_Shield=L_Shield)
✅

2023-11-17 14:21 UTC, Jun-Jiang-92 commented on AixLib/ThermalZones/HighOrder/Components/Shadow/ShadowEff.mo
> +    else=Use same reduce factor g_Shadow as direct radiation (no diffuse radiation when no shadow effect)";
✅

2023-11-17 14:21 UTC, Jun-Jiang-92 commented on AixLib/ThermalZones/HighOrder/Components/Shadow/ShadowEff.mo
> +  parameter Real C_I_diff(min=0,max=1) = 1 "Reduce factor of shadow effect for I_diff: 0=fully reduced, 1=no addtional reduce";
✅

2023-11-17 14:24 UTC, Jun-Jiang-92 commented on AixLib/ThermalZones/HighOrder/Components/Shadow/ShadowLength.mo
> +  parameter Modelica.Units.SI.Length L_Shield = 0.300 "Horizontal length of the sun shield";
✅

2023-11-17 14:29 UTC, Jun-Jiang-92 commented on AixLib/ThermalZones/HighOrder/Components/Shadow/ShadowEff.mo
> +
Here is an integration for each incidence angle, with a step size of pi/2 / 100.
Is it necessary to pack it into a function?
The number 100 could be set as a integration parameter N.

2023-11-17 14:53 UTC, Jun-Jiang-92 commented on AixLib/ThermalZones/HighOrder/Components/Shadow/Test.mo
> +  ShadowLength shadowLength
✅

2023-11-17 14:55 UTC, Jun-Jiang-92 commented on AixLib/ThermalZones/HighOrder/Components/Shadow/ShadowLength.mo
> +  if tan(zen.zen)<1e-5 or cos(wallSolAzi.verAzi)<1e-5 then
Using Modelica.Constants.eps doesn't works properly by calculation the condition, by which the shadow is not more presents.

2023-11-17 15:47 UTC, Jun-Jiang-92 commented on AixLib/ThermalZones/HighOrder/Components/Walls/Wall.mo
> +        iconTransformation(extent={{-29,-90},{-9,-70}})));
We must discuss about it.

2023-11-17 15:50 UTC, Jun-Jiang-92 commented on AixLib/ThermalZones/HighOrder/Components/Shadow/package.order
> +Test
✅

2023-11-28 17:42 UTC, Jun-Jiang-92 commented on AixLib/ThermalZones/HighOrder/Components/Shadow/WeaDatPrcs.mo
> +end WeaDatPrcs;
Keep the modul, renamed to "WeatherDataProcessing"

2023-11-28 17:45 UTC, Jun-Jiang-92 commented on AixLib/ThermalZones/HighOrder/Components/Shadow/ShadowLength.mo
> +  if tan(zen.zen)<1e-5 or cos(wallSolAzi.verAzi)<1e-5 then
Converted the model to the style based only on modus, there's no equations anymore.

2023-11-28 17:51 UTC, Jun-Jiang-92 commented on AixLib/ThermalZones/HighOrder/Components/Shadow/package.mo
> +
Added

2023-11-28 18:14 UTC, Jun-Jiang-92 commented on AixLib/ThermalZones/HighOrder/Components/Shadow/Test.mo
> +      __Dymola_Algorithm="Dassl"));
Added

2023-11-28 18:17 UTC, Jun-Jiang-92 commented on AixLib/ThermalZones/HighOrder/Components/Walls/Wall.mo
>    replaceable model WindowModel =
Checked the part where the shadow model integrated.

2023-12-11 14:39 UTC, Jun-Jiang-92 commented
@FWuellhorst I updated the codes as we discussed and renewed the pull request. If there is anything further that should be done here, please feel free to inform me.

2023-12-18 08:58 UTC, FWuellhorst commented
Thanks @Jun-Jiang-92 ! I updated the branch with the latest dev, and we have to check which regression tests are failing.

2023-12-18 13:33 UTC, FWuellhorst commented
@Jun-Jiang-92 : I made minor adjustments in your code. Everything looks good, except that a documentation is currently missing. Please indicate with 1-3 sentences what the models are used for and central assumptions. Also, add yourself to the revision section as done in other models and link #1433 .
Afterwards, you are free to merge! Nice work :)

2023-12-18 13:36 UTC, FWuellhorst commented
Regarding the failing tests: I don't get how they are failing, as the models did not change. If the current dev pipeline passes, I will look into this again. The only thing failing are the ASHREA cases:
```
Case950_AnnualCoolingLoad
Case220_AnnualHeatingLoad
Case210_AnnualHeatingLoad
Case250_AnnualHeatingLoad
Case430_AnnualHeatingLoad
Case400_AnnualHeatingLoad
Case410_AnnualHeatingLoad
Case420_AnnualHeatingLoad
Case800_AnnualHeatingLoad
```
The error is minimal, and other test cases run just fine, with no clear difference between e.g. Case200 and Case210 regarding wall / window models

2023-12-19 10:52 UTC, Jun-Jiang-92 commented
@FWuellhorst Thank you for your adjustments and checking failures.
I already added the documentation and revision info to the models. Since the test is still not able to pass, it is not possible to merge the changes into the branch directly. Is that right?
Would you like to show me how to merge it in this situation if you have any time?

2023-12-21 14:29 UTC, DaJansenGit commented
Is my review still required here? Since @FWuellhorst is already in the review process, I don't think so, right?

2024-01-12 14:58 UTC, FWuellhorst commented
@DaJansenGit No, your review is not required anymore. 
@Jun-Jiang-92 @DaJansenGit : I don't get why the regression tests fail, as the models do not use the shadow model. The errors are close to zero, an only certain variables are affected. I would opt to remove the existing regression files (.txt-files) to re-generate them by CI. Then, we can proceed and merge.

2024-01-15 07:59 UTC, FWuellhorst approved these changes
@Jun-Jiang-92 : Thnaks for the cool feature and the work associated with this! The CI passes now, and the changes look good. Feel free and click on merge :)

2024-01-15 08:21 UTC, merged