1426 non standard annotation phe
RWTH-EBC/AixLib pull request #1466
Opened 2023-09-19 09:16 UTC by TobiasSpratte

This pull request solves issue #1440. All instances of radioButtons in HOM are changed to enumerations. All hard-coded integer variables are changed to enumeration instances. There are more instances of radioButtons in the AixLib, which will be reworked in issue #1426.

2023-09-19 11:07 UTC, FWuellhorst requested changes
Thanks! Only minor comments.

2023-09-19 11:07 UTC, FWuellhorst commented on AixLib/BoundaryConditions/WeatherData/Old/WeatherTRY/Weather.mo
> +  parameter Boolean Outopt = false "Output individual vectors instead of one vector [-]" annotation(Dialog(tab = "Optional output vector", descriptionLabel = true), choices(checkBox = true));
outOpt?

2023-09-19 11:07 UTC, FWuellhorst commented on AixLib/ThermalZones/HighOrder/Components/Walls/BaseClasses/ConvNLayerClearanceStar.mo
> +        group="Convection", descriptionLabel=true));
Break lines to avoid long lines

2023-09-19 11:07 UTC, FWuellhorst commented on AixLib/ThermalZones/HighOrder/House/OFD_MiddleInnerLoadWall/BuildingEnvelope/UpperFloorBuildingEnvelope.mo
> +  connect(AirExchangePort[5], Children2.AirExchangePort) annotation (Line(points={{-115,-5},
In theory, all these changes of connections should not be in this PR. They look minor, and I don't know a method to cherry-pick-revert certain lines in a PR. Just for future commits, be sure to check if you changed the layout.

2023-09-19 14:11 UTC, FWuellhorst approved these changes
Thanks, looks nice :)

2024-01-24 07:44 UTC, PatrickHenkel1 commented
Tobias implemented the required changes from the last review, I fixed a wrong calculation method due to which the regression tests for HOM ASHRAE failed. I also changed the assignments in the pool model to enumerations

2024-01-25 09:14 UTC, FWuellhorst approved these changes

2024-01-25 10:03 UTC, merged