1520 new hp models
RWTH-EBC/AixLib pull request #1532
Opened 2024-08-19 13:53 UTC by FWuellhorst

Closes #1520

2024-08-27 15:46 UTC, FWuellhorst reviewed
@MZuschlag 
As discussed briefly already, I moved the old models to obsolete and adjusted the old performance data to the new format. This PR seems huge, but it is mainly moving the HeatPump, Chiller, and HeatPumpSystem to obsolete. Please check if the old examples still work for you (Obsolete is still tested in CI, so nothing changed) and if the new models, especially `AixLib.Fluid.HeatPumps.ModularReversible.RefrigerantCycle.TableData3D` is clear and useable. This was not yet reviewed in IBPSA.
If you have questions about the new approach and how to adopt your modules to it, we can also schedule a meeting.

2024-08-29 12:45 UTC, MZuschlag requested changes
See my comments

2024-08-29 12:45 UTC, MZuschlag commented on AixLib/Controls/HeatPump/BaseClasses/PartialTSetToNSet.mo
> +  parameter Modelica.Units.SI.Time movAveTime=360
Why the change?

2024-08-29 12:45 UTC, MZuschlag commented on AixLib/Electrical/PVSystem/BaseClasses/package.order
> +PartialIVCharacteristics
Why?

2024-08-29 13:06 UTC, FWuellhorst commented on AixLib/Electrical/PVSystem/BaseClasses/package.order
> +PartialIVCharacteristics
I fully moved it from package.mo to a separate file

2024-09-20 11:54 UTC, MZuschlag approved these changes
Mostly general question adressing heat pump modeling in general.

2024-09-20 11:54 UTC, MZuschlag commented on AixLib/Resources/Data/Fluid/HeatPumps/ModularReversible/Data/VCLibMap/create_vclib_map.py
> +        inputs=Inputs(T_con_in=273.15 + 47, T_eva_in=271.15, n=0.8, dT_eva_superheating=5, dT_con_subcooling=0),
Maybe we should change from n to frequency, because full-load is not always for the same frequency?

2024-09-20 11:54 UTC, MZuschlag commented on AixLib/Controls/HeatPump/Examples/InverterControlledHeatPump.mo
> +      bandwidth=2,
Why 2?

2024-09-20 11:54 UTC, MZuschlag commented on AixLib/Controls/HeatPump/InverterControlledHP.mo
>      final yMin=0)
Why 0 and not the lower boundary of n in the sdf?

2024-09-20 11:54 UTC, MZuschlag commented on AixLib/Fluid/HeatPumps/ModularReversible/Data/TableData2D/EN14511/AlphaInnotec_LW80MA.mo
> +    mCon_flow_nominal=9400/4180/5,
general question for all table-data: why not for maximum thermal power?

2024-09-20 11:54 UTC, MZuschlag commented on AixLib/Obsolete/Year2024/DataBase/Chiller/ChillerBaseDataDefinition.mo
> +    extends AixLib.Obsolete.Year2024.DataBase.HeatPump.HeatPumpBaseDataDefinition(tableQdot_con = tableQdot_eva);
Is this correct? Qdot_con=Qdt_eva, because condenser turns to evaporator from heating to cooling?

2024-09-20 11:54 UTC, MZuschlag commented on AixLib/Obsolete/Year2024/DataBase/Chiller/EN14511/Vitocal200AWO201.mo
>      tableP_ele=[0, 20, 25, 27, 30, 35; 7,1380.0, 1590.0, 1680.0, 1800.0, 1970.0;  18,950.0, 1060.0, 1130.0, 1200.0, 1350.0],
Celsius not Kelvin?

2024-09-20 11:54 UTC, MZuschlag commented on AixLib/Obsolete/Year2024/DataBase/Chiller/PerformanceData/LookUpTableND.mo
>    parameter Real nConv=100
if it is a gain, maybe dont call it n...

2024-09-20 11:54 UTC, MZuschlag commented on AixLib/Obsolete/Year2024/DataBase/HeatPump/EN14511/AlphaInnotec_LW80MA.mo
>      tableP_ele=[0,-7,2,7,10,15,20; 35,2625,2424,2410,2395,2347,2322; 45,3136,3053,
Celsius not Kelvin? check the others

2024-09-20 11:54 UTC, MZuschlag commented on AixLib/Obsolete/Year2024/DataBase/HeatPump/Functions/Characteristics/PartialBaseFct.mo
>    input Real N "Relative compressor speed";
why capital letter?

2024-09-20 17:51 UTC, FWuellhorst commented on AixLib/Resources/Data/Fluid/HeatPumps/ModularReversible/Data/VCLibMap/create_vclib_map.py
> +        inputs=Inputs(T_con_in=273.15 + 47, T_eva_in=271.15, n=0.8, dT_eva_superheating=5, dT_con_subcooling=0),
This is in VCLibPy, where the compressor always has N_max as a parameter to calculate the frequency / compressor speed. Comparing different heat pumps with different max speeds is easier for relative inputs I opted?

2024-09-20 17:52 UTC, FWuellhorst commented on AixLib/Controls/HeatPump/Examples/InverterControlledHeatPump.mo
> +      bandwidth=2,
I think 2 worked ok-ish, for the example, but I did not perform any detailed tests.

2024-09-20 17:53 UTC, FWuellhorst commented on AixLib/Controls/HeatPump/InverterControlledHP.mo
>      final yMin=0)
Good point, yMin=0 may actually lead to issues if the controller oscillates below the hysteresis value of the heat pump. I will use the nMin of the heat pump instead.

2024-09-20 17:54 UTC, FWuellhorst commented on AixLib/Fluid/HeatPumps/ModularReversible/Data/TableData2D/EN14511/AlphaInnotec_LW80MA.mo
> +    mCon_flow_nominal=9400/4180/5,
Good tables have the maximal power, this, for example, is a relict of the old model based on datasheets with only nominal values. I thought about just deleting all old options, but thought it is too much of a braking change.

2024-09-20 17:56 UTC, FWuellhorst commented on AixLib/Obsolete/Year2024/DataBase/Chiller/ChillerBaseDataDefinition.mo
> +    extends AixLib.Obsolete.Year2024.DataBase.HeatPump.HeatPumpBaseDataDefinition(tableQdot_con = tableQdot_eva);
Yes, I think this was the idea behind it. The new version clearly uses con and eva, the old Chiller versions had other issues, as well.

2024-09-20 17:56 UTC, FWuellhorst commented on AixLib/Obsolete/Year2024/DataBase/Chiller/EN14511/Vitocal200AWO201.mo
>      tableP_ele=[0, 20, 25, 27, 30, 35; 7,1380.0, 1590.0, 1680.0, 1800.0, 1970.0;  18,950.0, 1060.0, 1130.0, 1200.0, 1350.0],
Yes, those are the old models which were based on °C

2024-09-20 17:57 UTC, FWuellhorst commented on AixLib/Obsolete/Year2024/DataBase/HeatPump/EN14511/AlphaInnotec_LW80MA.mo
>      tableP_ele=[0,-7,2,7,10,15,20; 35,2625,2424,2410,2395,2347,2322; 45,3136,3053,
See my comment above

2024-09-20 17:59 UTC, FWuellhorst commented on AixLib/Obsolete/Year2024/DataBase/HeatPump/Functions/Characteristics/PartialBaseFct.mo
>    input Real N "Relative compressor speed";
mhm, I don't know. Could be a relict of older times. But it is now obsolete, so I would not rename it.

2024-09-20 18:03 UTC, FWuellhorst commented on AixLib/Obsolete/Year2024/DataBase/Chiller/PerformanceData/LookUpTableND.mo
>    parameter Real nConv=100
Good point, but as this model is now obsolete I would not rename it. The new version calls it `facGai` and it is a parameter of the data table. So you could add the maximum compressor speed / frequency to the record and still use the relative speed between 0 and 1 in Modelica :)

2024-09-26 14:45 UTC, MZuschlag approved these changes

2024-09-26 14:49 UTC, merged