Issue986 cooler on differnt setting
RWTH-EBC/AixLib pull request #987
Opened 2020-08-21 16:44 UTC by DaJansenGit

should solve the issue shown in #986 
closes #986

2020-08-24 06:23 UTC, KremerMartin requested changes
Updates on documentation in example.

2020-08-24 06:23 UTC, KremerMartin commented on AixLib/ThermalZones/ReducedOrder/Examples/MultizonePartlyCooled.mo
> +expected to fail.
Maybe we should change the documentraion here. Because we do not expect to fail the example anymore. ;)

2020-08-24 07:35 UTC, marcusfuchs commented
@DaJansenGit Thanks a lot for this fix. I can confirm that this also solves our original use case that lead us to find the bug reported in #986 .

2020-08-25 06:38 UTC, DaJansenGit commented on AixLib/ThermalZones/ReducedOrder/Examples/MultizonePartlyCooled.mo
> +expected to fail.
resoled with 0aa545d

2020-08-25 06:49 UTC, KremerMartin approved these changes

2020-08-25 12:49 UTC, merged