Issue797 add co2 concentration to rom
RWTH-EBC/AixLib pull request #989
Opened 2020-08-27 13:33 UTC by katharinabr

This is for #797.

Implementation of co2 balance for rom.
Update of fluid model to consider trace substances in thermal zone and multizone.
Manual merge of ibpsa changes to oneelement.

2020-08-27 14:06 UTC, KremerMartin requested changes
For successful check, the CO2-models have to be made conditional with the same condition as the ROM-model.
Some upper case parameters have to be changed to lower case.

2020-08-27 14:06 UTC, KremerMartin commented on AixLib/BoundaryConditions/InternalGains/CO2/CO2Balance.mo
> +  parameter Modelica.SIunits.Area AreaBod=1.8
should be lower case: areaBod

2020-08-27 14:06 UTC, KremerMartin commented on AixLib/BoundaryConditions/InternalGains/CO2/CO2Balance.mo
> +  parameter Modelica.SIunits.Area AreaZon "Zone area";
should be lower case

2020-08-27 14:06 UTC, KremerMartin commented on AixLib/ThermalZones/ReducedOrder/ThermalZone/ThermalZoneMoistCO2AirExchange.mo
> +  parameter Modelica.SIunits.Area AreaBod=1.8
lower case

2020-08-27 14:06 UTC, KremerMartin commented on AixLib/ThermalZones/ReducedOrder/ThermalZone/ThermalZoneMoistCO2AirExchange.mo
> +    AreaZon=zoneParam.AZone,
lower case

2020-08-27 14:06 UTC, KremerMartin commented on AixLib/ThermalZones/ReducedOrder/ThermalZone/ThermalZoneMoistCO2AirExchange.mo
> +    AreaBod=AreaBod,
lower case

2020-09-07 12:22 UTC, MartinRaetz commented
As @martinkremer made a thorough code check, I may test this implementation for its function in a use case. 
If I understood correctly, it should be usable besides the failing check?
(I will tackle this approximately next week)

2020-09-15 10:37 UTC, KremerMartin approved these changes

2020-09-15 10:49 UTC, KremerMartin commented
@katharinabr @MartinRaetz I have approved the changes. (Sorry, that it took me so long.) The ci is failing, as the checks for the thermal zone fail. I have no clue about that, because in dymola all checks are successful.

2020-10-26 15:05 UTC, MartinRaetz approved these changes

2020-10-26 15:12 UTC, merged